
# ---------------------------------------------------------------------------
# GROUP 6: Chicken kebabs & starters
# ---------------------------------------------------------------------------
CHICKEN_STARTERS = [
    {"en":"Chicken Tikka","bn":"চিকেন টিক্কা","cat":"chicken",
     "k":180,"p":28.0,"c":3.0,"f":6.0,"fi":0.2,"ca":15,"fe":1.0,
     "kw":["chicken","tikka","tandoor","starter","kebab","marinated"]},
    {"en":"Chicken Malai Tikka","bn":"চিকেন মালাই টিক্কা","cat":"chicken",
     "k":225,"p":24.0,"c":4.0,"f":13.0,"fi":0.2,"ca":35,"fe":0.8,
     "kw":["chicken","malai","tikka","cream","starter","tandoor","rich"]},
    {"en":"Chicken Reshmi Kebab","bn":"চিকেন রেশমি কাবাব","cat":"chicken",
     "k":215,"p":25.0,"c":4.0,"f":11.5,"fi":0.2,"ca":30,"fe":0.8,
     "kw":["chicken","reshmi","kebab","silky","starter","tandoor"]},
    {"en":"Chicken Seekh Kebab","bn":"চিকেন শিক কাবাব","cat":"chicken",
     "k":205,"p":22.0,"c":4.5,"f":11.0,"fi":0.5,"ca":25,"fe":1.0,
     "kw":["chicken","seekh","kebab","minced","skewer","tandoor"]},
    {"en":"Chicken Kalmi Kebab","bn":"চিকেন কালমি কাবাব","cat":"chicken",
     "k":230,"p":25.0,"c":2.5,"f":13.5,"fi":0.2,"ca":20,"fe":1.0,
     "kw":["chicken","kalmi","kebab","leg","tandoor","starter"]},
    {"en":"Chicken Tangdi Kebab","bn":"চিকেন তাংড়ি কাবাব","cat":"chicken",
     "k":215,"p":26.0,"c":2.0,"f":11.0,"fi":0.1,"ca":20,"fe":1.1,
     "kw":["chicken","tangdi","kebab","drumstick","tandoor","starter"]},
    {"en":"Tandoori Chicken","bn":"তন্দুরি চিকেন","cat":"chicken",
     "k":215,"p":30.0,"c":2.0,"f":9.0,"fi":0.1,"ca":18,"fe":1.2,
     "kw":["chicken","tandoori","tandoor","starter","red","popular","restaurant"]},
    {"en":"Chicken Lollipop","bn":"চিকেন ললিপপ","cat":"chicken",
     "k":285,"p":21.0,"c":11.0,"f":17.0,"fi":0.5,"ca":20,"fe":1.0,
     "kw":["chicken","lollipop","wing","fried","starter","party"]},
    {"en":"Chicken 65","bn":"চিকেন ৬৫","cat":"chicken",
     "k":265,"p":20.0,"c":10.0,"f":16.0,"fi":0.6,"ca":20,"fe":1.0,
     "kw":["chicken","65","south indian","spicy","fried","starter","popular"]},
    {"en":"Chicken Pakora","bn":"চিকেন পাকোড়া","cat":"chicken",
     "k":275,"p":19.0,"c":12.0,"f":18.0,"fi":0.7,"ca":25,"fe":1.0,
     "kw":["chicken","pakora","besan","fried","starter","snack"]},
    {"en":"Afghani Chicken Tikka","bn":"আফগানি চিকেন টিক্কা","cat":"chicken",
     "k":235,"p":25.4,"c":3.5,"f":13.2,"fi":0.2,"ca":30,"fe":0.8,
     "kw":["chicken","afghani","tikka","cream","starter","tandoor","rich"]},
    {"en":"Achari Chicken Tikka","bn":"আচারি চিকেন টিক্কা","cat":"chicken",
     "k":192,"p":27.6,"c":3.8,"f":7.4,"fi":0.4,"ca":22,"fe":1.0,
     "kw":["chicken","achari","tikka","pickle","tangy","starter","tandoor"]},
    {"en":"Hariyali Chicken Tikka","bn":"হরিয়ালি চিকেন টিক্কা","cat":"chicken",
     "k":186,"p":28.2,"c":3.2,"f":6.5,"fi":0.6,"ca":20,"fe":1.0,
     "kw":["chicken","hariyali","tikka","green","mint","coriander","starter"]},
    {"en":"Pahadi Chicken Tikka","bn":"পাহাড়ি চিকেন টিক্কা","cat":"chicken",
     "k":182,"p":28.8,"c":2.9,"f":6.2,"fi":0.5,"ca":20,"fe":1.0,
     "kw":["chicken","pahadi","tikka","mountain","mild","starter"]},
    {"en":"Murgh Malai Tikka","bn":"মুরগ মালাই টিক্কা","cat":"chicken",
     "k":228,"p":24.5,"c":4.2,"f":13.4,"fi":0.2,"ca":35,"fe":0.8,
     "kw":["chicken","murgh","malai","tikka","cream","rich","starter"]},
    {"en":"Murgh Angara","bn":"মুরগ আঙ্গারা","cat":"chicken",
     "k":205,"p":26.5,"c":4.1,"f":8.7,"fi":0.4,"ca":22,"fe":1.0,
     "kw":["chicken","murgh","angara","smoky","charcoal","starter"]},
    {"en":"Murgh Lasooni","bn":"মুরগ লাসুনি","cat":"chicken",
     "k":196,"p":27.2,"c":3.8,"f":7.6,"fi":0.3,"ca":20,"fe":1.0,
     "kw":["chicken","murgh","lasooni","garlic","starter","tandoor"]},
    {"en":"Murgh Nawabi","bn":"মুরগ নবাবি","cat":"chicken",
     "k":232,"p":24.8,"c":4.5,"f":13.5,"fi":0.2,"ca":35,"fe":0.8,
     "kw":["chicken","murgh","nawabi","rich","mughlai","starter"]},
    {"en":"Murgh Kastoori","bn":"মুরগ কস্তুরি","cat":"chicken",
     "k":208,"p":26.4,"c":3.9,"f":9.2,"fi":0.4,"ca":22,"fe":1.0,
     "kw":["chicken","murgh","kastoori","methi","fenugreek","starter"]},
    {"en":"Murgh Gilafi","bn":"মুরগ গিলাফি","cat":"chicken",
     "k":214,"p":24.2,"c":6.2,"f":10.4,"fi":1.2,"ca":25,"fe":1.0,
     "kw":["chicken","murgh","gilafi","vegetable","colourful","seekh"]},
    {"en":"Chicken Banjara","bn":"চিকেন বাঞ্জারা","cat":"chicken",
     "k":202,"p":26.8,"c":3.8,"f":8.4,"fi":0.4,"ca":20,"fe":1.0,
     "kw":["chicken","banjara","tribal","spicy","starter","tandoor"]},
    {"en":"Chicken Bhuna Kebab","bn":"চিকেন ভুনা কাবাব","cat":"chicken",
     "k":212,"p":25.6,"c":4.5,"f":9.8,"fi":0.5,"ca":22,"fe":1.0,
     "kw":["chicken","bhuna","kebab","dry","spicy","starter"]},
    {"en":"Chicken Barra","bn":"চিকেন বাররা","cat":"chicken",
     "k":218,"p":25.1,"c":3.6,"f":11.2,"fi":0.2,"ca":20,"fe":1.0,
     "kw":["chicken","barra","chop","marinated","tandoor","starter"]},
    {"en":"Murgh Irani","bn":"মুরগ ইরানি","cat":"chicken",
     "k":224,"p":24.3,"c":4.4,"f":12.6,"fi":0.3,"ca":28,"fe":0.8,
     "kw":["chicken","murgh","irani","persian","cream","starter"]},
    {"en":"Murgh Zafrani","bn":"মুরগ জাফরানি","cat":"chicken",
     "k":220,"p":24.8,"c":4.1,"f":11.8,"fi":0.2,"ca":28,"fe":0.8,
     "kw":["chicken","murgh","zafrani","saffron","golden","starter"]},
    {"en":"Murgh Hariyali Seekh","bn":"মুরগ হরিয়ালি শিক","cat":"chicken",
     "k":198,"p":22.6,"c":5.3,"f":9.4,"fi":0.8,"ca":22,"fe":1.0,
     "kw":["chicken","murgh","hariyali","seekh","green","minced","starter"]},
    {"en":"Chicken Cafreal","bn":"চিকেন ক্যাফ্রিয়াল","cat":"chicken",
     "k":188,"p":27.4,"c":2.8,"f":7.2,"fi":0.6,"ca":20,"fe":1.0,
     "kw":["chicken","cafreal","goan","green","spicy","starter","portuguese"]},
    {"en":"Chicken Ghee Roast","bn":"চিকেন ঘি রোস্ট","cat":"chicken",
     "k":286,"p":23.5,"c":4.6,"f":19.8,"fi":0.5,"ca":20,"fe":1.2,
     "kw":["chicken","ghee roast","mangalorean","starter","spicy","rich"]},
    {"en":"Chilli Chicken Dry","bn":"চিলি চিকেন ড্রাই","cat":"chicken",
     "k":245,"p":21.0,"c":10.0,"f":13.0,"fi":0.5,"ca":20,"fe":1.0,
     "kw":["chicken","chilli","dry","indo chinese","starter","spicy","popular"]},
    {"en":"Dragon Chicken","bn":"ড্রাগন চিকেন","cat":"chicken",
     "k":270,"p":20.0,"c":13.0,"f":15.0,"fi":0.6,"ca":20,"fe":1.0,
     "kw":["chicken","dragon","indo chinese","spicy","starter","crispy"]},
    {"en":"Pepper Chicken","bn":"পেপার চিকেন","cat":"chicken",
     "k":210,"p":24.0,"c":4.0,"f":10.0,"fi":0.3,"ca":18,"fe":1.0,
     "kw":["chicken","pepper","starter","south indian","dry","spicy"]},
]

# ---------------------------------------------------------------------------
# GROUP 7: Mutton kebabs & starters
# ---------------------------------------------------------------------------
MUTTON_STARTERS = [
    {"en":"Mutton Seekh Kebab","bn":"মাটন শিক কাবাব","cat":"mutton",
     "k":285,"p":19.0,"c":5.0,"f":20.0,"fi":0.5,"ca":20,"fe":2.5,
     "kw":["mutton","seekh","kebab","minced","skewer","tandoor","starter"]},
    {"en":"Shami Kebab","bn":"শামি কাবাব","cat":"mutton",
     "k":255,"p":18.0,"c":9.0,"f":16.0,"fi":1.2,"ca":25,"fe":2.2,
     "kw":["mutton","shami","kebab","minced","chana dal","starter","awadhi"]},
    {"en":"Galouti Kebab","bn":"গালৌটি কাবাব","cat":"mutton",
     "k":315,"p":17.0,"c":5.0,"f":25.0,"fi":0.4,"ca":18,"fe":2.0,
     "kw":["mutton","galouti","kebab","melt mouth","awadhi","lucknow","starter"]},
    {"en":"Kakori Kebab","bn":"কাকোরি কাবাব","cat":"mutton",
     "k":290,"p":18.0,"c":4.0,"f":22.0,"fi":0.3,"ca":18,"fe":2.0,
     "kw":["mutton","kakori","kebab","awadhi","lucknow","starter","skewer"]},
    {"en":"Boti Kebab","bn":"বোটি কাবাব","cat":"mutton",
     "k":265,"p":23.0,"c":2.0,"f":18.0,"fi":0.2,"ca":15,"fe":2.2,
     "kw":["mutton","boti","kebab","chunk","tandoor","marinated","starter"]},
    {"en":"Gola Kebab","bn":"গোলা কাবাব","cat":"mutton",
     "k":305,"p":18.0,"c":5.0,"f":24.0,"fi":0.4,"ca":18,"fe":2.0,
     "kw":["mutton","gola","kebab","minced","starter"]},
    {"en":"Bihari Kebab","bn":"বিহারি কাবাব","cat":"mutton",
     "k":260,"p":24.0,"c":3.0,"f":17.0,"fi":0.3,"ca":18,"fe":2.2,
     "kw":["mutton","bihari","kebab","starter","flat","marinated"]},
    {"en":"Shikampuri Kebab","bn":"শিকামপুরি কাবাব","cat":"mutton",
     "k":295,"p":18.0,"c":6.0,"f":22.0,"fi":0.5,"ca":20,"fe":2.0,
     "kw":["mutton","shikampuri","kebab","stuffed","hyderabadi","starter"]},
    {"en":"Burrah Kebab","bn":"বুররা কাবাব","cat":"mutton",
     "k":298,"p":24.5,"c":2.4,"f":21.2,"fi":0.2,"ca":18,"fe":2.2,
     "kw":["mutton","burrah","kebab","chop","tandoor","starter"]},
    {"en":"Chapli Kebab","bn":"চাপলি কাবাব","cat":"mutton",
     "k":285,"p":19.8,"c":8.2,"f":19.5,"fi":1.4,"ca":25,"fe":2.0,
     "kw":["mutton","chapli","kebab","peshwari","afghani","flat","starter"]},
    {"en":"Pasanda Kebab","bn":"পাসান্দা কাবাব","cat":"mutton",
     "k":272,"p":22.4,"c":4.6,"f":18.2,"fi":0.3,"ca":18,"fe":2.0,
     "kw":["mutton","pasanda","kebab","flat","marinated","starter"]},
    {"en":"Pathar Ka Gosht","bn":"পাথর কা গোশত","cat":"mutton",
     "k":301,"p":24.8,"c":2.3,"f":21.6,"fi":0.2,"ca":18,"fe":2.2,
     "kw":["mutton","pathar","gosht","stone","cooked","hyderabadi","starter"]},
    {"en":"Raan Roast","bn":"রান রোস্ট","cat":"mutton",
     "k":282,"p":25.5,"c":2.2,"f":18.6,"fi":0.2,"ca":18,"fe":2.5,
     "kw":["mutton","raan","roast","leg","whole","dum","starter","festive"]},
    {"en":"Dum Kebab","bn":"দম কাবাব","cat":"mutton",
     "k":276,"p":21.8,"c":5.4,"f":18.4,"fi":0.4,"ca":20,"fe":2.0,
     "kw":["mutton","dum","kebab","slow cooked","starter"]},
    {"en":"Tunday Kebab","bn":"টুন্ডে কাবাব","cat":"mutton",
     "k":318,"p":18.6,"c":4.8,"f":25.8,"fi":0.3,"ca":18,"fe":2.0,
     "kw":["mutton","tunday","kebab","lucknow","awadhi","melt","starter"]},
    {"en":"Lucknowi Seekh Kebab","bn":"লখনৌ শিক কাবাব","cat":"mutton",
     "k":289,"p":20.5,"c":5.6,"f":20.4,"fi":0.5,"ca":20,"fe":2.2,
     "kw":["mutton","lucknowi","seekh","kebab","awadhi","tender","starter"]},
    {"en":"Hyderabadi Seekh Kebab","bn":"হায়দরাবাদি শিক কাবাব","cat":"mutton",
     "k":295,"p":20.2,"c":5.8,"f":21.0,"fi":0.6,"ca":20,"fe":2.2,
     "kw":["mutton","hyderabadi","seekh","kebab","spicy","starter"]},
    {"en":"Bhuna Gosht Starter","bn":"ভুনা গোশত","cat":"mutton",
     "k":268,"p":22.8,"c":4.2,"f":17.6,"fi":0.4,"ca":18,"fe":2.2,
     "kw":["mutton","bhuna","gosht","dry","spicy","starter"]},
    {"en":"Afghani Mutton Kebab","bn":"আফগানি মাটন কাবাব","cat":"mutton",
     "k":296,"p":22.2,"c":3.8,"f":21.0,"fi":0.2,"ca":18,"fe":2.0,
     "kw":["mutton","afghani","kebab","cream","rich","starter"]},
    {"en":"Achari Mutton Kebab","bn":"আচারি মাটন কাবাব","cat":"mutton",
     "k":281,"p":22.5,"c":3.9,"f":18.8,"fi":0.3,"ca":18,"fe":2.0,
     "kw":["mutton","achari","kebab","pickle","tangy","starter"]},
    {"en":"Hariyali Mutton Kebab","bn":"হরিয়ালি মাটন কাবাব","cat":"mutton",
     "k":274,"p":23.2,"c":3.5,"f":17.9,"fi":0.5,"ca":18,"fe":2.0,
     "kw":["mutton","hariyali","kebab","green","mint","starter"]},
    {"en":"Lasooni Mutton Kebab","bn":"লাসুনি মাটন কাবাব","cat":"mutton",
     "k":279,"p":22.8,"c":3.8,"f":18.5,"fi":0.4,"ca":18,"fe":2.0,
     "kw":["mutton","lasooni","kebab","garlic","starter"]},
    {"en":"Mutton Barra Kebab","bn":"মাটন বাররা কাবাব","cat":"mutton",
     "k":308,"p":24.0,"c":2.6,"f":22.0,"fi":0.2,"ca":18,"fe":2.2,
     "kw":["mutton","barra","kebab","chop","tandoor","starter"]},
    {"en":"Mutton Chaap Roast","bn":"মাটন চাঁপ রোস্ট","cat":"mutton",
     "k":315,"p":23.6,"c":2.5,"f":23.4,"fi":0.2,"ca":18,"fe":2.2,
     "kw":["mutton","chaap","roast","rib","starter"]},
    {"en":"Mutton Pepper Fry","bn":"মাটন পেপার ফ্রাই","cat":"mutton",
     "k":248,"p":22.6,"c":3.6,"f":15.6,"fi":0.5,"ca":18,"fe":2.5,
     "kw":["mutton","pepper","fry","dry","spicy","south indian","starter"]},
    {"en":"Mutton Sukka","bn":"মাটন সুক্কা","cat":"mutton",
     "k":258,"p":21.8,"c":4.5,"f":16.8,"fi":0.8,"ca":18,"fe":2.2,
     "kw":["mutton","sukka","dry","south indian","chettinad","starter"]},
    {"en":"Mutton Roast","bn":"মাটন রোস্ট","cat":"mutton",
     "k":270,"p":24.6,"c":2.8,"f":18.2,"fi":0.3,"ca":18,"fe":2.2,
     "kw":["mutton","roast","dry","spicy","starter","kerala"]},
    {"en":"Mutton Fry","bn":"মাটন ফ্রাই","cat":"mutton",
     "k":262,"p":22.5,"c":4.2,"f":17.0,"fi":0.4,"ca":18,"fe":2.2,
     "kw":["mutton","fry","dry","spicy","starter"]},
    {"en":"Mutton Chops","bn":"মাটন চপস","cat":"mutton",
     "k":312,"p":23.8,"c":2.1,"f":23.6,"fi":0.2,"ca":18,"fe":2.2,
     "kw":["mutton","chops","rib","grilled","starter"]},
    {"en":"Bhuna Mutton Chops","bn":"ভুনা মাটন চপস","cat":"mutton",
     "k":296,"p":23.4,"c":3.0,"f":21.0,"fi":0.3,"ca":18,"fe":2.2,
     "kw":["mutton","bhuna","chops","dry","spicy","starter"]},
]

# ---------------------------------------------------------------------------
# GROUP 8: Seafood starters
# ---------------------------------------------------------------------------
SEAFOOD_STARTERS = [
    {"en":"Fish Tikka","bn":"ফিশ টিক্কা","cat":"seafood",
     "k":165,"p":24.0,"c":3.0,"f":6.0,"fi":0.2,"ca":30,"fe":0.8,
     "kw":["fish","tikka","tandoor","starter","marinated","kebab"]},
    {"en":"Fish Amritsari","bn":"ফিশ অমৃতসরি","cat":"seafood",
     "k":235,"p":18.0,"c":13.0,"f":13.0,"fi":0.7,"ca":35,"fe":0.8,
     "kw":["fish","amritsari","punjabi","fried","batter","starter"]},
    {"en":"Prawn Tikka","bn":"চিংড়ি টিক্কা","cat":"seafood",
     "k":170,"p":25.0,"c":3.0,"f":6.0,"fi":0.2,"ca":60,"fe":1.5,
     "kw":["prawn","shrimp","tikka","tandoor","starter","kebab"]},
    {"en":"Tandoori Prawns","bn":"তন্দুরি চিংড়ি","cat":"seafood",
     "k":180,"p":26.0,"c":3.0,"f":6.5,"fi":0.2,"ca":65,"fe":1.6,
     "kw":["prawn","shrimp","tandoori","tandoor","starter"]},
    {"en":"Pomfret Tikka","bn":"পমফ্রেট টিক্কা","cat":"seafood",
     "k":172,"p":23.8,"c":3.2,"f":7.0,"fi":0.2,"ca":40,"fe":0.8,
     "kw":["pomfret","tikka","fish","tandoor","starter","coastal"]},
    {"en":"Surmai Tikka","bn":"সুরমাই টিক্কা","cat":"seafood",
     "k":184,"p":24.5,"c":2.8,"f":8.2,"fi":0.2,"ca":35,"fe":0.8,
     "kw":["surmai","kingfish","tikka","tandoor","starter"]},
    {"en":"Tandoori Pomfret","bn":"তন্দুরি পমফ্রেট","cat":"seafood",
     "k":178,"p":24.0,"c":2.5,"f":7.5,"fi":0.2,"ca":40,"fe":0.8,
     "kw":["pomfret","tandoori","fish","tandoor","whole","starter"]},
    {"en":"Fish Hariyali","bn":"ফিশ হরিয়ালি","cat":"seafood",
     "k":168,"p":24.2,"c":3.6,"f":6.4,"fi":0.5,"ca":32,"fe":0.8,
     "kw":["fish","hariyali","green","mint","coriander","starter"]},
    {"en":"Fish Malai Tikka","bn":"ফিশ মালাই টিক্কা","cat":"seafood",
     "k":212,"p":22.4,"c":4.2,"f":12.5,"fi":0.2,"ca":40,"fe":0.8,
     "kw":["fish","malai","tikka","cream","rich","starter"]},
    {"en":"Prawn Koliwada","bn":"চিংড়ি কোলিওয়াড়া","cat":"seafood",
     "k":242,"p":20.5,"c":12.4,"f":12.8,"fi":0.8,"ca":65,"fe":1.5,
     "kw":["prawn","koliwada","fried","spicy","maharashtrian","starter"]},
    {"en":"Tandoori Crab","bn":"তন্দুরি কাঁকড়া","cat":"seafood",
     "k":164,"p":23.8,"c":2.8,"f":6.2,"fi":0.2,"ca":70,"fe":1.0,
     "kw":["crab","tandoori","tandoor","starter","coastal"]},
    {"en":"Calamari Fry","bn":"ক্যালামারি ফ্রাই","cat":"seafood",
     "k":226,"p":17.8,"c":13.5,"f":11.6,"fi":0.8,"ca":30,"fe":0.8,
     "kw":["calamari","squid","fried","starter","continental"]},
    {"en":"Garlic Butter Prawns","bn":"গার্লিক বাটার চিংড়ি","cat":"seafood",
     "k":238,"p":22.6,"c":3.5,"f":15.2,"fi":0.2,"ca":70,"fe":1.5,
     "kw":["prawn","garlic","butter","starter","continental","rich"]},
    {"en":"Achari Fish Tikka","bn":"আচারি ফিশ টিক্কা","cat":"seafood",
     "k":176,"p":24.2,"c":3.8,"f":7.0,"fi":0.3,"ca":32,"fe":0.8,
     "kw":["fish","achari","tikka","pickle","tangy","starter"]},
    {"en":"Afghani Fish Tikka","bn":"আফগানি ফিশ টিক্কা","cat":"seafood",
     "k":214,"p":22.8,"c":4.0,"f":12.6,"fi":0.2,"ca":35,"fe":0.8,
     "kw":["fish","afghani","tikka","cream","rich","starter"]},
    {"en":"Hariyali Prawns","bn":"হরিয়ালি চিংড়ি","cat":"seafood",
     "k":175,"p":24.8,"c":3.0,"f":7.2,"fi":0.3,"ca":65,"fe":1.5,
     "kw":["prawn","hariyali","green","mint","starter"]},
    {"en":"Malai Prawns","bn":"মালাই চিংড়ি","cat":"seafood",
     "k":226,"p":22.5,"c":4.4,"f":13.6,"fi":0.2,"ca":70,"fe":1.5,
     "kw":["prawn","malai","cream","rich","starter"]},
    {"en":"Prawn Pepper Fry","bn":"চিংড়ি পেপার ফ্রাই","cat":"seafood",
     "k":196,"p":23.2,"c":4.5,"f":9.2,"fi":0.5,"ca":65,"fe":1.5,
     "kw":["prawn","pepper","fry","dry","spicy","south indian","starter"]},
    {"en":"Prawn Ghee Roast","bn":"চিংড়ি ঘি রোস্ট","cat":"seafood",
     "k":268,"p":22.4,"c":5.8,"f":17.8,"fi":0.6,"ca":65,"fe":1.5,
     "kw":["prawn","ghee roast","mangalorean","rich","spicy","starter"]},
    {"en":"Fish Fry","bn":"ফিশ ফ্রাই","cat":"seafood",
     "k":236,"p":20.6,"c":11.5,"f":13.5,"fi":0.7,"ca":35,"fe":0.8,
     "kw":["fish","fry","fried","starter","popular","bengali","coastal"]},
    {"en":"Fish Fingers","bn":"ফিশ ফিঙ্গার","cat":"seafood",
     "k":248,"p":18.5,"c":16.4,"f":12.8,"fi":1.0,"ca":35,"fe":0.8,
     "kw":["fish","fingers","breaded","fried","starter","kids","popular"]},
    {"en":"Crab Pepper Fry","bn":"কাঁকড়া পেপার ফ্রাই","cat":"seafood",
     "k":182,"p":21.5,"c":4.5,"f":8.6,"fi":0.4,"ca":70,"fe":1.0,
     "kw":["crab","pepper","fry","spicy","south indian","starter"]},
    {"en":"Crab Masala Fry","bn":"কাঁকড়া মসলা ফ্রাই","cat":"seafood",
     "k":194,"p":20.8,"c":5.6,"f":9.8,"fi":0.5,"ca":70,"fe":1.0,
     "kw":["crab","masala","fry","spicy","starter","coastal"]},
    {"en":"Butter Garlic Crab","bn":"বাটার গার্লিক কাঁকড়া","cat":"seafood",
     "k":228,"p":21.4,"c":3.8,"f":14.6,"fi":0.2,"ca":75,"fe":1.0,
     "kw":["crab","butter","garlic","rich","starter","coastal","goa"]},
    {"en":"Squid Pepper Fry","bn":"স্কুইড পেপার ফ্রাই","cat":"seafood",
     "k":192,"p":18.8,"c":5.2,"f":10.2,"fi":0.4,"ca":30,"fe":0.8,
     "kw":["squid","calamari","pepper","fry","starter","south indian"]},
    {"en":"Squid Ghee Roast","bn":"স্কুইড ঘি রোস্ট","cat":"seafood",
     "k":258,"p":18.5,"c":5.8,"f":18.2,"fi":0.5,"ca":30,"fe":0.8,
     "kw":["squid","calamari","ghee roast","mangalorean","starter","rich"]},
    {"en":"Prawn 65","bn":"চিংড়ি ৬৫","cat":"seafood",
     "k":252,"p":20.8,"c":12.2,"f":13.8,"fi":0.8,"ca":65,"fe":1.5,
     "kw":["prawn","65","south indian","spicy","fried","starter"]},
    {"en":"Fish 65","bn":"ফিশ ৬৫","cat":"seafood",
     "k":244,"p":19.6,"c":12.6,"f":13.2,"fi":0.8,"ca":35,"fe":0.8,
     "kw":["fish","65","south indian","spicy","fried","starter"]},
    {"en":"Prawn Tempura","bn":"চিংড়ি টেম্পুরা","cat":"seafood",
     "k":238,"p":18.2,"c":17.5,"f":11.8,"fi":0.7,"ca":65,"fe":1.5,
     "kw":["prawn","tempura","japanese","batter","fried","starter"]},
    {"en":"Crispy Fried Prawns","bn":"ক্রিসপি ফ্রাইড চিংড়ি","cat":"seafood",
     "k":246,"p":19.4,"c":15.8,"f":12.5,"fi":0.7,"ca":65,"fe":1.5,
     "kw":["prawn","crispy","fried","batter","starter","popular"]},
]

# ---------------------------------------------------------------------------
# GROUP 9: Paneer starters
# ---------------------------------------------------------------------------
PANEER_STARTERS = [
    {"en":"Paneer Tikka","bn":"পনির টিক্কা","cat":"paneer",
     "k":265,"p":16.0,"c":8.0,"f":19.0,"fi":1.1,"ca":480,"fe":0.8,
     "kw":["paneer","tikka","tandoor","starter","vegetarian","popular"]},
    {"en":"Paneer Malai Tikka","bn":"পনির মালাই টিক্কা","cat":"paneer",
     "k":295,"p":15.0,"c":8.0,"f":23.0,"fi":1.0,"ca":470,"fe":0.7,
     "kw":["paneer","malai","tikka","cream","rich","tandoor","starter"]},
    {"en":"Achari Paneer Tikka","bn":"আচারি পনির টিক্কা","cat":"paneer",
     "k":272,"p":15.8,"c":8.6,"f":19.6,"fi":1.4,"ca":480,"fe":0.8,
     "kw":["paneer","achari","tikka","pickle","tangy","tandoor","starter"]},
    {"en":"Paneer Hariyali","bn":"পনির হরিয়ালি","cat":"paneer",
     "k":258,"p":16.5,"c":7.8,"f":18.2,"fi":1.6,"ca":480,"fe":0.8,
     "kw":["paneer","hariyali","green","mint","coriander","starter"]},
    {"en":"Paneer Lasooni","bn":"পনির লাসুনি","cat":"paneer",
     "k":276,"p":16.2,"c":8.4,"f":20.1,"fi":1.3,"ca":480,"fe":0.8,
     "kw":["paneer","lasooni","garlic","tandoor","starter"]},
    {"en":"Paneer Angara","bn":"পনির আঙ্গারা","cat":"paneer",
     "k":281,"p":16.0,"c":9.2,"f":20.3,"fi":1.5,"ca":480,"fe":0.8,
     "kw":["paneer","angara","smoky","charcoal","tandoor","starter"]},
    {"en":"Paneer Kastoori","bn":"পনির কস্তুরি","cat":"paneer",
     "k":269,"p":16.4,"c":8.0,"f":19.2,"fi":1.5,"ca":480,"fe":0.8,
     "kw":["paneer","kastoori","methi","fenugreek","tandoor","starter"]},
    {"en":"Paneer Nawabi","bn":"পনির নবাবি","cat":"paneer",
     "k":298,"p":15.2,"c":9.8,"f":22.5,"fi":1.2,"ca":470,"fe":0.7,
     "kw":["paneer","nawabi","rich","mughlai","cream","starter"]},
    {"en":"Paneer Afghani","bn":"পনির আফগানি","cat":"paneer",
     "k":305,"p":15.0,"c":8.8,"f":23.8,"fi":1.1,"ca":470,"fe":0.7,
     "kw":["paneer","afghani","cream","rich","starter","white marinade"]},
    {"en":"Paneer Reshmi Tikka","bn":"পনির রেশমি টিক্কা","cat":"paneer",
     "k":286,"p":15.8,"c":8.5,"f":21.5,"fi":1.1,"ca":475,"fe":0.7,
     "kw":["paneer","reshmi","tikka","silky","cream","starter"]},
    {"en":"Paneer Pahadi Tikka","bn":"পনির পাহাড়ি টিক্কা","cat":"paneer",
     "k":258,"p":16.3,"c":7.6,"f":18.4,"fi":1.6,"ca":480,"fe":0.8,
     "kw":["paneer","pahadi","tikka","mountain","mild","green","starter"]},
    {"en":"Paneer Pudina Tikka","bn":"পনির পুদিনা টিক্কা","cat":"paneer",
     "k":254,"p":16.2,"c":7.8,"f":18.0,"fi":1.7,"ca":480,"fe":0.8,
     "kw":["paneer","pudina","mint","tikka","fresh","starter"]},
    {"en":"Paneer Kali Mirch","bn":"পনির কালো মরিচ","cat":"paneer",
     "k":270,"p":16.0,"c":8.0,"f":19.5,"fi":1.2,"ca":480,"fe":0.8,
     "kw":["paneer","kali mirch","black pepper","starter","spicy"]},
    {"en":"Paneer Chatpata","bn":"পনির চাটপটা","cat":"paneer",
     "k":268,"p":15.8,"c":9.4,"f":18.9,"fi":1.8,"ca":475,"fe":0.8,
     "kw":["paneer","chatpata","tangy","spicy","starter"]},
    {"en":"Paneer Shashlik","bn":"পনির শাশলিক","cat":"paneer",
     "k":262,"p":15.9,"c":10.8,"f":18.0,"fi":2.3,"ca":470,"fe":0.8,
     "kw":["paneer","shashlik","skewer","vegetable","colourful","starter"]},
    {"en":"Paneer Gilafi","bn":"পনির গিলাফি","cat":"paneer",
     "k":286,"p":15.6,"c":10.6,"f":20.8,"fi":2.1,"ca":470,"fe":0.8,
     "kw":["paneer","gilafi","vegetable coated","seekh","starter"]},
    {"en":"Paneer Tandoori","bn":"পনির তন্দুরি","cat":"paneer",
     "k":260,"p":16.3,"c":7.8,"f":18.6,"fi":1.2,"ca":480,"fe":0.8,
     "kw":["paneer","tandoori","tandoor","starter","classic","marinated"]},
    {"en":"Paneer Seekh Kebab","bn":"পনির শিক কাবাব","cat":"paneer",
     "k":248,"p":13.8,"c":13.5,"f":15.6,"fi":2.4,"ca":340,"fe":0.9,
     "kw":["paneer","seekh","kebab","minced","skewer","vegetarian","starter"]},
    {"en":"Paneer Haryali Seekh","bn":"পনির হরিয়ালি শিক","cat":"paneer",
     "k":242,"p":13.5,"c":12.8,"f":15.2,"fi":2.6,"ca":340,"fe":0.9,
     "kw":["paneer","hariyali","seekh","green","minced","skewer","starter"]},
    {"en":"Paneer Cheese Tikka","bn":"পনির চিজ টিক্কা","cat":"paneer",
     "k":322,"p":17.2,"c":8.2,"f":25.6,"fi":1.0,"ca":560,"fe":0.6,
     "kw":["paneer","cheese","tikka","rich","indulgent","starter"]},
    {"en":"Stuffed Paneer Tikka","bn":"স্টাফড পনির টিক্কা","cat":"paneer",
     "k":289,"p":16.8,"c":9.8,"f":21.2,"fi":1.5,"ca":480,"fe":0.8,
     "kw":["paneer","stuffed","tikka","filling","starter"]},
    {"en":"Paneer 65","bn":"পনির ৬৫","cat":"paneer",
     "k":298,"p":14.5,"c":15.2,"f":20.5,"fi":1.4,"ca":420,"fe":0.8,
     "kw":["paneer","65","south indian","spicy","fried","starter"]},
    {"en":"Chilli Paneer Dry","bn":"চিলি পনির ড্রাই","cat":"paneer",
     "k":276,"p":14.8,"c":14.5,"f":18.6,"fi":1.7,"ca":420,"fe":0.8,
     "kw":["paneer","chilli","dry","indo chinese","starter","popular","spicy"]},
    {"en":"Dragon Paneer","bn":"ড্রাগন পনির","cat":"paneer",
     "k":292,"p":14.2,"c":16.4,"f":19.8,"fi":1.8,"ca":415,"fe":0.8,
     "kw":["paneer","dragon","indo chinese","spicy","starter","crispy"]},
    {"en":"Crispy Paneer","bn":"ক্রিসপি পনির","cat":"paneer",
     "k":315,"p":13.8,"c":18.2,"f":22.4,"fi":1.6,"ca":410,"fe":0.8,
     "kw":["paneer","crispy","fried","starter","crunchy"]},
    {"en":"Paneer Pakoda","bn":"পনির পাকোড়া","cat":"paneer",
     "k":318,"p":13.5,"c":15.8,"f":22.8,"fi":1.4,"ca":410,"fe":0.8,
     "kw":["paneer","pakoda","besan","fried","starter","snack"]},
    {"en":"Paneer Popcorn","bn":"পনির পপকর্ন","cat":"paneer",
     "k":326,"p":13.2,"c":18.6,"f":23.5,"fi":1.5,"ca":405,"fe":0.8,
     "kw":["paneer","popcorn","bite sized","fried","starter","kids"]},
    {"en":"Paneer Fingers","bn":"পনির ফিঙ্গার","cat":"paneer",
     "k":320,"p":13.8,"c":18.4,"f":22.8,"fi":1.6,"ca":408,"fe":0.8,
     "kw":["paneer","fingers","breaded","fried","starter"]},
]

# ---------------------------------------------------------------------------
# GROUP 10: Soya chaap starters
# ---------------------------------------------------------------------------
SOYA_STARTERS = [
    {"en":"Tandoori Soya Chaap","bn":"তন্দুরি সয়া চাঁপ","cat":"vegetarian",
     "k":212,"p":19.2,"c":11.6,"f":10.4,"fi":3.4,"ca":120,"fe":3.0,
     "kw":["soya","chaap","tandoori","starter","veg","high protein"]},
    {"en":"Achari Soya Chaap","bn":"আচারি সয়া চাঁপ","cat":"vegetarian",
     "k":218,"p":18.8,"c":12.4,"f":11.2,"fi":3.6,"ca":118,"fe":3.0,
     "kw":["soya","chaap","achari","pickle","tangy","starter"]},
    {"en":"Hariyali Soya Chaap","bn":"হরিয়ালি সয়া চাঁপ","cat":"vegetarian",
     "k":205,"p":19.6,"c":11.2,"f":9.5,"fi":3.8,"ca":122,"fe":3.0,
     "kw":["soya","chaap","hariyali","green","mint","starter"]},
    {"en":"Masala Soya Chaap","bn":"মসলা সয়া চাঁপ","cat":"vegetarian",
     "k":228,"p":18.4,"c":13.8,"f":12.0,"fi":3.5,"ca":116,"fe":2.8,
     "kw":["soya","chaap","masala","spiced","starter"]},
    {"en":"Tawa Soya Chaap","bn":"তাওয়া সয়া চাঁপ","cat":"vegetarian",
     "k":236,"p":18.2,"c":12.5,"f":13.4,"fi":3.3,"ca":115,"fe":2.8,
     "kw":["soya","chaap","tawa","griddle","starter"]},
    {"en":"Peri Peri Soya Chaap","bn":"পেরি পেরি সয়া চাঁপ","cat":"vegetarian",
     "k":224,"p":18.8,"c":13.6,"f":11.4,"fi":3.4,"ca":116,"fe":2.8,
     "kw":["soya","chaap","peri peri","spicy","starter"]},
    {"en":"Schezwan Soya Chaap","bn":"শেজওয়ান সয়া চাঁপ","cat":"vegetarian",
     "k":232,"p":18.0,"c":15.2,"f":11.8,"fi":3.2,"ca":114,"fe":2.8,
     "kw":["soya","chaap","schezwan","indo chinese","spicy","starter"]},
    {"en":"Malai Soya Chaap","bn":"মালাই সয়া চাঁপ","cat":"vegetarian",
     "k":248,"p":18.2,"c":11.4,"f":15.4,"fi":3.1,"ca":130,"fe":2.8,
     "kw":["soya","chaap","malai","cream","rich","starter"]},
    {"en":"Afghani Soya Chaap","bn":"আফগানি সয়া চাঁপ","cat":"vegetarian",
     "k":252,"p":17.8,"c":11.8,"f":16.2,"fi":3.0,"ca":128,"fe":2.8,
     "kw":["soya","chaap","afghani","cream","rich","white","starter"]},
    {"en":"Reshmi Soya Chaap","bn":"রেশমি সয়া চাঁপ","cat":"vegetarian",
     "k":242,"p":18.0,"c":11.6,"f":14.6,"fi":3.1,"ca":126,"fe":2.8,
     "kw":["soya","chaap","reshmi","silky","cream","starter"]},
    {"en":"Lasooni Soya Chaap","bn":"লাসুনি সয়া চাঁপ","cat":"vegetarian",
     "k":221,"p":18.9,"c":12.4,"f":11.2,"fi":3.5,"ca":118,"fe":2.8,
     "kw":["soya","chaap","lasooni","garlic","starter"]},
    {"en":"Angara Soya Chaap","bn":"আঙ্গারা সয়া চাঁপ","cat":"vegetarian",
     "k":229,"p":18.4,"c":12.8,"f":12.2,"fi":3.3,"ca":116,"fe":2.8,
     "kw":["soya","chaap","angara","smoky","charcoal","starter"]},
    {"en":"Nawabi Soya Chaap","bn":"নবাবি সয়া চাঁপ","cat":"vegetarian",
     "k":246,"p":17.9,"c":12.5,"f":15.0,"fi":3.1,"ca":126,"fe":2.8,
     "kw":["soya","chaap","nawabi","rich","mughlai","starter"]},
    {"en":"Gilafi Soya Chaap","bn":"গিলাফি সয়া চাঁপ","cat":"vegetarian",
     "k":234,"p":18.2,"c":14.6,"f":11.6,"fi":4.1,"ca":116,"fe":2.8,
     "kw":["soya","chaap","gilafi","vegetable","colourful","starter"]},
    {"en":"Pudina Soya Chaap","bn":"পুদিনা সয়া চাঁপ","cat":"vegetarian",
     "k":208,"p":19.4,"c":11.5,"f":9.8,"fi":3.7,"ca":120,"fe":3.0,
     "kw":["soya","chaap","pudina","mint","fresh","starter"]},
    {"en":"Lemon Pepper Soya Chaap","bn":"লেমন পেপার সয়া চাঁপ","cat":"vegetarian",
     "k":214,"p":19.1,"c":11.8,"f":10.2,"fi":3.5,"ca":118,"fe":2.8,
     "kw":["soya","chaap","lemon","pepper","starter","tangy"]},
    {"en":"Smoked Soya Chaap","bn":"স্মোকড সয়া চাঁপ","cat":"vegetarian",
     "k":220,"p":18.8,"c":12.0,"f":11.0,"fi":3.4,"ca":116,"fe":2.8,
     "kw":["soya","chaap","smoked","bbq","starter"]},
    {"en":"Butter Masala Soya Chaap","bn":"বাটার মসলা সয়া চাঁপ","cat":"vegetarian",
     "k":262,"p":17.4,"c":13.2,"f":17.0,"fi":3.2,"ca":130,"fe":2.8,
     "kw":["soya","chaap","butter","masala","rich","starter"]},
    {"en":"Soya Chaap Seekh Kebab","bn":"সয়া চাঁপ শিক কাবাব","cat":"vegetarian",
     "k":205,"p":20.4,"c":12.6,"f":8.8,"fi":4.2,"ca":122,"fe":3.0,
     "kw":["soya","chaap","seekh","kebab","skewer","starter","veg","high protein"]},
    {"en":"Soya Chaap Tikka","bn":"সয়া চাঁপ টিক্কা","cat":"vegetarian",
     "k":210,"p":19.8,"c":11.8,"f":10.0,"fi":3.8,"ca":120,"fe":3.0,
     "kw":["soya","chaap","tikka","tandoor","starter","veg"]},
    {"en":"Crispy Soya Chaap","bn":"ক্রিসপি সয়া চাঁপ","cat":"vegetarian",
     "k":276,"p":17.5,"c":18.2,"f":15.6,"fi":3.4,"ca":114,"fe":2.8,
     "kw":["soya","chaap","crispy","fried","starter"]},
    {"en":"Soya Chaap 65","bn":"সয়া চাঁপ ৬৫","cat":"vegetarian",
     "k":268,"p":17.8,"c":17.4,"f":14.8,"fi":3.2,"ca":114,"fe":2.8,
     "kw":["soya","chaap","65","south indian style","spicy","fried","starter"]},
    {"en":"Chilli Soya Chaap","bn":"চিলি সয়া চাঁপ","cat":"vegetarian",
     "k":244,"p":18.0,"c":16.2,"f":11.8,"fi":3.6,"ca":114,"fe":2.8,
     "kw":["soya","chaap","chilli","indo chinese","spicy","starter"]},
    {"en":"Dragon Soya Chaap","bn":"ড্রাগন সয়া চাঁপ","cat":"vegetarian",
     "k":258,"p":17.5,"c":18.5,"f":13.2,"fi":3.4,"ca":112,"fe":2.8,
     "kw":["soya","chaap","dragon","indo chinese","spicy","starter"]},
    {"en":"Punjabi Soya Chaap","bn":"পাঞ্জাবি সয়া চাঁপ","cat":"vegetarian",
     "k":238,"p":18.1,"c":13.0,"f":13.5,"fi":3.3,"ca":116,"fe":2.8,
     "kw":["soya","chaap","punjabi","spiced","dhaba","starter"]},
    {"en":"Kastoori Soya Chaap","bn":"কস্তুরি সয়া চাঁপ","cat":"vegetarian",
     "k":226,"p":18.5,"c":12.2,"f":11.8,"fi":3.4,"ca":116,"fe":2.8,
     "kw":["soya","chaap","kastoori","methi","fenugreek","starter"]},
    {"en":"Mint Soya Chaap","bn":"মিন্ট সয়া চাঁপ","cat":"vegetarian",
     "k":206,"p":19.5,"c":11.4,"f":9.6,"fi":3.8,"ca":120,"fe":3.0,
     "kw":["soya","chaap","mint","fresh","starter","cooling"]},
    {"en":"Spicy Tandoori Chaap","bn":"স্পাইসি তন্দুরি চাঁপ","cat":"vegetarian",
     "k":216,"p":19.0,"c":12.2,"f":10.6,"fi":3.4,"ca":118,"fe":2.8,
     "kw":["soya","chaap","spicy","tandoori","hot","starter"]},
    {"en":"Chatpata Soya Chaap","bn":"চাটপটা সয়া চাঁপ","cat":"vegetarian",
     "k":223,"p":18.6,"c":13.5,"f":11.3,"fi":3.5,"ca":116,"fe":2.8,
     "kw":["soya","chaap","chatpata","tangy","spicy","starter"]},
    {"en":"Creamy Soya Chaap","bn":"ক্রিমি সয়া চাঁপ","cat":"vegetarian",
     "k":255,"p":17.8,"c":12.4,"f":16.2,"fi":3.1,"ca":128,"fe":2.8,
     "kw":["soya","chaap","creamy","cream","rich","starter"]},
]

# ---------------------------------------------------------------------------
# GROUP 11: Vegetarian starters & kebabs
# ---------------------------------------------------------------------------
VEG_STARTERS = [
    {"en":"Hara Bhara Kebab","bn":"হরা ভরা কাবাব","cat":"vegetarian",
     "k":185,"p":5.0,"c":20.0,"f":9.0,"fi":4.0,"ca":80,"fe":2.5,
     "kw":["veg","kebab","hara bhara","spinach","peas","green","starter"]},
    {"en":"Veg Seekh Kebab","bn":"ভেজ শিক কাবাব","cat":"vegetarian",
     "k":175,"p":5.5,"c":22.0,"f":8.0,"fi":3.8,"ca":50,"fe":1.5,
     "kw":["veg","seekh","kebab","minced","skewer","vegetarian","starter"]},
    {"en":"Dahi Kebab","bn":"দহি কাবাব","cat":"vegetarian",
     "k":245,"p":10.0,"c":14.0,"f":16.0,"fi":0.8,"ca":220,"fe":0.5,
     "kw":["dahi","kebab","hung curd","yogurt","creamy","starter","veg"]},
    {"en":"Rajma Kebab","bn":"রাজমা কাবাব","cat":"vegetarian",
     "k":190,"p":8.0,"c":24.0,"f":7.0,"fi":6.0,"ca":42,"fe":4.0,
     "kw":["rajma","kidney bean","kebab","veg","starter","high fiber"]},
    {"en":"Corn Tikki","bn":"কর্ন টিক্কি","cat":"vegetarian",
     "k":198,"p":5.8,"c":28.6,"f":7.2,"fi":4.5,"ca":15,"fe":0.8,
     "kw":["corn","tikki","pattie","veg","starter","sweet"]},
    {"en":"Beetroot Kebab","bn":"বিটরুট কাবাব","cat":"vegetarian",
     "k":176,"p":4.6,"c":24.2,"f":6.5,"fi":5.8,"ca":20,"fe":1.8,
     "kw":["beetroot","beet","kebab","veg","starter","healthy","colourful"]},
    {"en":"Spinach Corn Kebab","bn":"পালং কর্ন কাবাব","cat":"vegetarian",
     "k":185,"p":6.4,"c":23.8,"f":7.0,"fi":4.8,"ca":80,"fe":2.5,
     "kw":["spinach","corn","kebab","veg","starter","healthy","green"]},
    {"en":"Broccoli Tikka","bn":"ব্রকোলি টিক্কা","cat":"vegetarian",
     "k":132,"p":5.6,"c":12.4,"f":6.2,"fi":3.8,"ca":40,"fe":0.8,
     "kw":["broccoli","tikka","veg","starter","healthy","tandoor","low cal"]},
    {"en":"Stuffed Capsicum","bn":"স্টাফড ক্যাপসিকাম","cat":"vegetarian",
     "k":148,"p":5.2,"c":15.6,"f":7.0,"fi":3.9,"ca":25,"fe":0.8,
     "kw":["capsicum","bell pepper","stuffed","veg","starter"]},
    {"en":"Cheese Cigars","bn":"চিজ সিগার","cat":"vegetarian",
     "k":328,"p":10.8,"c":22.6,"f":21.8,"fi":1.2,"ca":280,"fe":0.6,
     "kw":["cheese","cigar","roll","starter","party","crispy"]},
    {"en":"Veg Shami Kebab","bn":"ভেজ শামি কাবাব","cat":"vegetarian",
     "k":188,"p":7.2,"c":22.4,"f":7.8,"fi":5.4,"ca":45,"fe":2.0,
     "kw":["veg","shami","kebab","lentil","chana","starter"]},
    {"en":"Mushroom Galouti","bn":"মাশরুম গালৌটি","cat":"vegetarian",
     "k":172,"p":6.8,"c":16.5,"f":8.6,"fi":3.4,"ca":15,"fe":0.8,
     "kw":["mushroom","galouti","veg","kebab","starter","melt"]},
    {"en":"Mushroom Tikka","bn":"মাশরুম টিক্কা","cat":"vegetarian",
     "k":142,"p":6.5,"c":10.2,"f":8.2,"fi":2.6,"ca":12,"fe":0.6,
     "kw":["mushroom","tikka","veg","starter","tandoor","healthy"]},
    {"en":"Stuffed Mushroom","bn":"স্টাফড মাশরুম","cat":"vegetarian",
     "k":188,"p":8.0,"c":12.5,"f":11.8,"fi":2.8,"ca":60,"fe":0.8,
     "kw":["mushroom","stuffed","veg","starter","cheese","baked"]},
    {"en":"Mushroom Pepper Fry","bn":"মাশরুম পেপার ফ্রাই","cat":"vegetarian",
     "k":146,"p":5.8,"c":9.8,"f":9.0,"fi":2.7,"ca":12,"fe":0.6,
     "kw":["mushroom","pepper","fry","veg","starter","south indian"]},
    {"en":"Baby Corn Tikka","bn":"বেবি কর্ন টিক্কা","cat":"vegetarian",
     "k":156,"p":5.2,"c":18.4,"f":7.2,"fi":3.6,"ca":12,"fe":0.5,
     "kw":["baby corn","tikka","veg","starter","tandoor"]},
    {"en":"Baby Corn Pepper Fry","bn":"বেবি কর্ন পেপার ফ্রাই","cat":"vegetarian",
     "k":162,"p":4.8,"c":19.5,"f":7.8,"fi":3.9,"ca":12,"fe":0.5,
     "kw":["baby corn","pepper","fry","veg","starter"]},
    {"en":"Veg Galouti Kebab","bn":"ভেজ গালৌটি কাবাব","cat":"vegetarian",
     "k":182,"p":6.6,"c":21.6,"f":7.6,"fi":4.8,"ca":40,"fe":2.0,
     "kw":["veg","galouti","kebab","melt","starter","lentil"]},
    {"en":"Rajma Galouti Kebab","bn":"রাজমা গালৌটি কাবাব","cat":"vegetarian",
     "k":174,"p":8.4,"c":22.8,"f":6.2,"fi":5.8,"ca":42,"fe":4.0,
     "kw":["rajma","kidney bean","galouti","kebab","starter"]},
    {"en":"Lentil Kebab","bn":"ডাল কাবাব","cat":"vegetarian",
     "k":180,"p":8.8,"c":24.0,"f":5.8,"fi":6.2,"ca":40,"fe":2.5,
     "kw":["lentil","dal","kebab","veg","starter","high fiber","protein"]},
    {"en":"Cheese Balls","bn":"চিজ বলস","cat":"vegetarian",
     "k":306,"p":10.2,"c":20.4,"f":20.8,"fi":1.4,"ca":280,"fe":0.5,
     "kw":["cheese","balls","starter","fried","party","kids"]},
    {"en":"Veg Cutlet","bn":"ভেজ কাটলেট","cat":"vegetarian",
     "k":192,"p":4.8,"c":24.8,"f":8.4,"fi":3.8,"ca":30,"fe":1.0,
     "kw":["veg","cutlet","fried","starter","bengali","snack"]},
    {"en":"Vegetable Tikka","bn":"সবজির টিক্কা","cat":"vegetarian",
     "k":138,"p":5.4,"c":13.5,"f":6.5,"fi":3.8,"ca":30,"fe":0.8,
     "kw":["vegetable","tikka","veg","tandoor","starter","healthy","colourful"]},
    {"en":"Tandoori Broccoli","bn":"তন্দুরি ব্রকোলি","cat":"vegetarian",
     "k":128,"p":5.8,"c":11.2,"f":6.0,"fi":3.9,"ca":40,"fe":0.8,
     "kw":["broccoli","tandoori","veg","starter","healthy","low cal"]},
    {"en":"Crispy Corn","bn":"ক্রিসপি কর্ন","cat":"street_food",
     "k":248,"p":5.4,"c":34.2,"f":10.6,"fi":4.6,"ca":5,"fe":0.5,
     "kw":["crispy","corn","starter","fried","popular","street food"]},
    {"en":"Cheese Stuffed Potato","bn":"চিজ স্টাফড পটেটো","cat":"vegetarian",
     "k":254,"p":8.2,"c":24.5,"f":14.2,"fi":3.0,"ca":160,"fe":0.8,
     "kw":["cheese","potato","stuffed","starter","baked","rich"]},
    {"en":"Broccoli Cheese Balls","bn":"ব্রকোলি চিজ বলস","cat":"vegetarian",
     "k":236,"p":8.6,"c":18.4,"f":14.2,"fi":3.2,"ca":180,"fe":0.8,
     "kw":["broccoli","cheese","balls","starter","fried","healthy snack"]},
    {"en":"Cheese Corn Balls","bn":"চিজ কর্ন বলস","cat":"vegetarian",
     "k":310,"p":9.0,"c":24.0,"f":20.0,"fi":2.0,"ca":200,"fe":0.5,
     "kw":["cheese","corn","balls","starter","fried","party","kids"]},
    {"en":"Veg Pakora","bn":"ভেজ পাকোড়া","cat":"street_food",
     "k":265,"p":6.0,"c":22.0,"f":17.0,"fi":3.0,"ca":40,"fe":1.5,
     "kw":["veg","pakora","besan","fried","starter","street food","snack"]},
    {"en":"Onion Bhaji","bn":"পেঁয়াজ ভাজি","cat":"street_food",
     "k":250,"p":5.0,"c":24.0,"f":15.0,"fi":3.5,"ca":35,"fe":1.2,
     "kw":["onion","bhaji","pakora","fried","starter","indian","street food"]},
    {"en":"Paneer Pakora","bn":"পনির পাকোড়া","cat":"paneer",
     "k":315,"p":13.0,"c":15.0,"f":22.0,"fi":1.0,"ca":420,"fe":0.7,
     "kw":["paneer","pakoda","pakora","fried","starter","besan","snack"]},
    {"en":"Aloo Tikki","bn":"আলুর টিক্কি","cat":"street_food",
     "k":195,"p":4.0,"c":28.0,"f":8.0,"fi":3.5,"ca":20,"fe":1.0,
     "kw":["aloo","tikki","potato","fried","street food","chaat","starter","popular"]},
    {"en":"Honey Chilli Potato","bn":"হানি চিলি পটেটো","cat":"street_food",
     "k":245,"p":3.0,"c":36.0,"f":10.0,"fi":3.0,"ca":15,"fe":0.8,
     "kw":["honey","chilli","potato","crispy","indo chinese","starter","popular"]},
    {"en":"Spring Roll","bn":"স্প্রিং রোল","cat":"street_food",
     "k":240,"p":5.0,"c":30.0,"f":11.0,"fi":2.5,"ca":20,"fe":0.8,
     "kw":["spring roll","chinese","fried","starter","veg","crispy"]},
]

# ---------------------------------------------------------------------------
# GROUP 12: Indo-Chinese starters
# ---------------------------------------------------------------------------
INDO_CHINESE = [
    {"en":"Gobi Manchurian Dry","bn":"ফুলকপি মাঞ্চুরিয়ান ড্রাই","cat":"street_food",
     "k":196,"p":4.8,"c":24.6,"f":9.2,"fi":3.4,"ca":25,"fe":0.8,
     "kw":["gobi","cauliflower","manchurian","dry","indo chinese","starter","veg"]},
    {"en":"Gobi Manchurian Gravy","bn":"ফুলকপি মাঞ্চুরিয়ান গ্রেভি","cat":"street_food",
     "k":142,"p":3.8,"c":17.6,"f":6.2,"fi":2.8,"ca":20,"fe":0.7,
     "kw":["gobi","cauliflower","manchurian","gravy","indo chinese","veg"]},
    {"en":"Chilli Mushroom","bn":"চিলি মাশরুম","cat":"street_food",
     "k":164,"p":6.4,"c":15.2,"f":8.4,"fi":3.2,"ca":12,"fe":0.6,
     "kw":["mushroom","chilli","indo chinese","starter","spicy","veg"]},
    {"en":"Chilli Baby Corn","bn":"চিলি বেবি কর্ন","cat":"street_food",
     "k":182,"p":4.8,"c":23.6,"f":8.0,"fi":4.1,"ca":12,"fe":0.5,
     "kw":["baby corn","chilli","indo chinese","starter","spicy","veg"]},
    {"en":"Crispy Veg","bn":"ক্রিসপি ভেজ","cat":"street_food",
     "k":218,"p":5.2,"c":28.8,"f":10.2,"fi":4.2,"ca":30,"fe":1.0,
     "kw":["crispy","veg","vegetable","indo chinese","starter","fried"]},
    {"en":"Crispy Spinach","bn":"ক্রিসপি পালং","cat":"street_food",
     "k":248,"p":5.0,"c":24.6,"f":14.8,"fi":4.6,"ca":80,"fe":2.5,
     "kw":["crispy","spinach","palak","fried","starter","indo chinese"]},
    {"en":"Gobi 65","bn":"ফুলকপি ৬৫","cat":"street_food",
     "k":204,"p":5.4,"c":25.2,"f":9.8,"fi":3.6,"ca":25,"fe":0.8,
     "kw":["gobi","cauliflower","65","south indian","spicy","fried","starter"]},
    {"en":"Veg 65","bn":"ভেজ ৬৫","cat":"street_food",
     "k":196,"p":5.6,"c":24.5,"f":8.8,"fi":4.0,"ca":28,"fe":1.0,
     "kw":["veg","65","south indian","spicy","fried","mixed vegetable","starter"]},
    {"en":"Mushroom 65","bn":"মাশরুম ৬৫","cat":"street_food",
     "k":182,"p":6.5,"c":19.8,"f":8.5,"fi":3.2,"ca":12,"fe":0.6,
     "kw":["mushroom","65","south indian","spicy","fried","starter"]},
    {"en":"Baby Corn 65","bn":"বেবি কর্ন ৬৫","cat":"street_food",
     "k":205,"p":4.8,"c":26.4,"f":9.2,"fi":4.0,"ca":12,"fe":0.5,
     "kw":["baby corn","65","south indian","spicy","fried","starter"]},
    {"en":"Chilli Paneer Gravy","bn":"চিলি পনির গ্রেভি","cat":"paneer",
     "k":214,"p":13.8,"c":12.8,"f":13.5,"fi":1.5,"ca":400,"fe":0.7,
     "kw":["paneer","chilli","gravy","indo chinese","popular","restaurant"]},
    {"en":"Dragon Mushroom","bn":"ড্রাগন মাশরুম","cat":"street_food",
     "k":196,"p":6.2,"c":20.5,"f":9.4,"fi":3.4,"ca":12,"fe":0.6,
     "kw":["mushroom","dragon","indo chinese","spicy","starter"]},
    {"en":"Dragon Baby Corn","bn":"ড্রাগন বেবি কর্ন","cat":"street_food",
     "k":208,"p":4.6,"c":27.2,"f":9.2,"fi":4.2,"ca":12,"fe":0.5,
     "kw":["baby corn","dragon","indo chinese","spicy","starter"]},
    {"en":"Dragon Veg","bn":"ড্রাগন ভেজ","cat":"street_food",
     "k":214,"p":5.2,"c":27.8,"f":9.8,"fi":4.4,"ca":28,"fe":1.0,
     "kw":["veg","dragon","indo chinese","spicy","starter","mixed"]},
    {"en":"Honey Chilli Baby Corn","bn":"হানি চিলি বেবি কর্ন","cat":"street_food",
     "k":214,"p":4.5,"c":31.2,"f":8.2,"fi":4.1,"ca":12,"fe":0.5,
     "kw":["honey","chilli","baby corn","indo chinese","starter","sweet spicy"]},
    {"en":"Salt and Pepper Corn","bn":"সল্ট অ্যান্ড পেপার কর্ন","cat":"street_food",
     "k":208,"p":5.6,"c":28.4,"f":8.4,"fi":4.2,"ca":5,"fe":0.5,
     "kw":["salt pepper","corn","starter","indo chinese","simple"]},
    {"en":"Salt and Pepper Mushroom","bn":"সল্ট অ্যান্ড পেপার মাশরুম","cat":"street_food",
     "k":176,"p":6.6,"c":16.8,"f":8.2,"fi":3.3,"ca":12,"fe":0.6,
     "kw":["salt pepper","mushroom","starter","indo chinese"]},
    {"en":"Salt and Pepper Baby Corn","bn":"সল্ট অ্যান্ড পেপার বেবি কর্ন","cat":"street_food",
     "k":188,"p":5.0,"c":22.6,"f":8.0,"fi":4.0,"ca":12,"fe":0.5,
     "kw":["salt pepper","baby corn","starter","indo chinese"]},
    {"en":"Veg Manchurian Dry","bn":"ভেজ মাঞ্চুরিয়ান ড্রাই","cat":"street_food",
     "k":198,"p":5.4,"c":25.8,"f":8.6,"fi":4.1,"ca":28,"fe":1.0,
     "kw":["veg","manchurian","dry","indo chinese","starter","popular"]},
    {"en":"Veg Manchurian Gravy","bn":"ভেজ মাঞ্চুরিয়ান গ্রেভি","cat":"street_food",
     "k":154,"p":4.8,"c":18.2,"f":6.4,"fi":3.6,"ca":22,"fe":0.8,
     "kw":["veg","manchurian","gravy","indo chinese","popular"]},
    {"en":"Mushroom Manchurian","bn":"মাশরুম মাঞ্চুরিয়ান","cat":"street_food",
     "k":176,"p":6.5,"c":18.4,"f":8.0,"fi":3.2,"ca":12,"fe":0.6,
     "kw":["mushroom","manchurian","indo chinese","starter"]},
    {"en":"Baby Corn Manchurian","bn":"বেবি কর্ন মাঞ্চুরিয়ান","cat":"street_food",
     "k":186,"p":5.0,"c":22.8,"f":8.2,"fi":4.0,"ca":12,"fe":0.5,
     "kw":["baby corn","manchurian","indo chinese","starter"]},
    {"en":"Chilli Garlic Mushroom","bn":"চিলি গার্লিক মাশরুম","cat":"street_food",
     "k":170,"p":6.8,"c":15.8,"f":8.0,"fi":3.2,"ca":12,"fe":0.6,
     "kw":["mushroom","chilli","garlic","indo chinese","starter","spicy"]},
    {"en":"Schezwan Vegetables","bn":"শেজওয়ান সবজি","cat":"street_food",
     "k":142,"p":4.6,"c":15.8,"f":6.2,"fi":3.8,"ca":30,"fe":1.0,
     "kw":["schezwan","vegetables","indo chinese","spicy","starter"]},
    {"en":"Vegetable Spring Roll","bn":"ভেজিটেবল স্প্রিং রোল","cat":"street_food",
     "k":232,"p":5.6,"c":28.8,"f":10.5,"fi":3.6,"ca":20,"fe":0.8,
     "kw":["vegetable","spring roll","indo chinese","fried","starter"]},
]

# ---------------------------------------------------------------------------
# GROUP 13: Regional starters
# ---------------------------------------------------------------------------
REGIONAL_STARTERS = [
    {"en":"Hyderabadi Chicken Tikka","bn":"হায়দরাবাদি চিকেন টিক্কা","cat":"chicken",
     "k":204,"p":26.2,"c":4.2,"f":8.6,"fi":0.4,"ca":20,"fe":1.0,
     "kw":["chicken","hyderabadi","tikka","spicy","starter","south indian"]},
    {"en":"Awadhi Galouti Kebab","bn":"আওয়াধি গালৌটি কাবাব","cat":"mutton",
     "k":314,"p":18.2,"c":4.8,"f":25.4,"fi":0.3,"ca":18,"fe":2.0,
     "kw":["mutton","awadhi","galouti","kebab","lucknow","melt","starter"]},
    {"en":"Awadhi Murgh Tikka","bn":"আওয়াধি মুরগ টিক্কা","cat":"chicken",
     "k":216,"p":25.8,"c":4.1,"f":10.2,"fi":0.3,"ca":20,"fe":1.0,
     "kw":["chicken","awadhi","tikka","lucknow","starter","mild"]},
    {"en":"Murgh Afghani","bn":"মুরগ আফগানি","cat":"chicken",
     "k":235,"p":25.4,"c":3.5,"f":13.2,"fi":0.2,"ca":28,"fe":0.8,
     "kw":["chicken","murgh","afghani","cream","starter","rich","white marinade"]},
    {"en":"Mughlai Seekh Kebab","bn":"মুঘলাই শিক কাবাব","cat":"mutton",
     "k":286,"p":20.8,"c":5.0,"f":20.2,"fi":0.4,"ca":20,"fe":2.0,
     "kw":["mutton","mughlai","seekh","kebab","rich","starter"]},
    {"en":"Mughlai Boti Kebab","bn":"মুঘলাই বোটি কাবাব","cat":"mutton",
     "k":274,"p":24.0,"c":3.2,"f":18.4,"fi":0.2,"ca":15,"fe":2.2,
     "kw":["mutton","mughlai","boti","kebab","starter","marinated"]},
    {"en":"Kashmiri Mutton Seekh","bn":"কাশ্মীরি মাটন শিক","cat":"mutton",
     "k":282,"p":21.5,"c":4.8,"f":19.6,"fi":0.4,"ca":18,"fe":2.0,
     "kw":["mutton","kashmiri","seekh","kebab","starter","mild spices"]},
    {"en":"Kashmiri Chicken Tikka","bn":"কাশ্মীরি চিকেন টিক্কা","cat":"chicken",
     "k":196,"p":27.4,"c":3.6,"f":7.2,"fi":0.3,"ca":18,"fe":1.0,
     "kw":["chicken","kashmiri","tikka","mild","red","starter"]},
    {"en":"Chicken Tikka Punjabi","bn":"পাঞ্জাবি চিকেন টিক্কা","cat":"chicken",
     "k":192,"p":27.6,"c":3.8,"f":7.4,"fi":0.4,"ca":20,"fe":1.0,
     "kw":["chicken","punjabi","tikka","tandoor","starter","classic"]},
    {"en":"Amritsari Fish","bn":"অমৃতসরি মাছ","cat":"seafood",
     "k":232,"p":19.2,"c":12.8,"f":12.6,"fi":0.8,"ca":35,"fe":0.8,
     "kw":["fish","amritsari","punjabi","fried","batter","carom","ajwain","starter"]},
    {"en":"Rajasthani Laal Maas Starter","bn":"রাজস্থানি লাল মাংস স্টার্টার","cat":"mutton",
     "k":248,"p":22.6,"c":4.5,"f":15.6,"fi":0.5,"ca":18,"fe":2.5,
     "kw":["mutton","rajasthani","laal maas","red","spicy","starter"]},
    {"en":"Jungli Maas","bn":"জঙ্গলি মাংস","cat":"mutton",
     "k":238,"p":23.8,"c":2.2,"f":15.2,"fi":0.2,"ca":15,"fe":2.5,
     "kw":["mutton","jungli maas","rajasthani","simple","rustic","starter"]},
    {"en":"Bengali Fish Fry","bn":"বাংলা ফিশ ফ্রাই","cat":"seafood",
     "k":248,"p":18.8,"c":16.4,"f":12.5,"fi":0.8,"ca":35,"fe":0.8,
     "kw":["fish","bengali","fry","fried","bengal","starter","popular"]},
    {"en":"Fish Kabiraji","bn":"ফিশ কাবিরাজি","cat":"seafood",
     "k":266,"p":17.8,"c":18.6,"f":14.2,"fi":0.7,"ca":35,"fe":0.8,
     "kw":["fish","kabiraji","bengali","egg coated","fried","starter","kolkata"]},
    {"en":"Goan Chicken Cafreal","bn":"গোয়ান চিকেন ক্যাফ্রিয়াল","cat":"chicken",
     "k":188,"p":27.4,"c":2.8,"f":7.2,"fi":0.6,"ca":18,"fe":1.0,
     "kw":["chicken","goan","cafreal","green","portuguese","starter","goa"]},
    {"en":"Goan Prawn Balchao","bn":"গোয়ান চিংড়ি বালচাও","cat":"seafood",
     "k":184,"p":22.8,"c":5.2,"f":8.2,"fi":0.5,"ca":65,"fe":1.5,
     "kw":["prawn","goan","balchao","pickled","spicy","starter","goa"]},
    {"en":"Goan Rava Fried Fish","bn":"গোয়ান রাভা ফ্রাইড ফিশ","cat":"seafood",
     "k":242,"p":19.8,"c":13.8,"f":12.4,"fi":1.1,"ca":35,"fe":0.8,
     "kw":["fish","goan","rava","semolina","fried","starter","crispy"]},
    {"en":"Mangalorean Chicken Ghee Roast","bn":"মাঙ্গালোর চিকেন ঘি রোস্ট","cat":"chicken",
     "k":286,"p":23.5,"c":4.6,"f":19.8,"fi":0.5,"ca":18,"fe":1.2,
     "kw":["chicken","mangalorean","ghee roast","spicy","coastal","starter"]},
    {"en":"Mangalorean Prawn Ghee Roast","bn":"মাঙ্গালোর চিংড়ি ঘি রোস্ট","cat":"seafood",
     "k":268,"p":22.4,"c":5.8,"f":17.8,"fi":0.6,"ca":65,"fe":1.5,
     "kw":["prawn","mangalorean","ghee roast","spicy","coastal","starter"]},
    {"en":"Mangalorean Fish Fry","bn":"মাঙ্গালোর ফিশ ফ্রাই","cat":"seafood",
     "k":236,"p":20.6,"c":11.5,"f":13.5,"fi":0.7,"ca":35,"fe":0.8,
     "kw":["fish","mangalorean","fry","spicy","masala","coastal","starter"]},
    {"en":"Malabar Fish Fry","bn":"মালাবার ফিশ ফ্রাই","cat":"seafood",
     "k":234,"p":20.2,"c":10.8,"f":13.6,"fi":0.6,"ca":35,"fe":0.8,
     "kw":["fish","malabar","kerala","fry","spicy","coastal","starter"]},
    {"en":"Malabar Prawn Fry","bn":"মালাবার চিংড়ি ফ্রাই","cat":"seafood",
     "k":226,"p":22.5,"c":6.5,"f":13.2,"fi":0.5,"ca":65,"fe":1.5,
     "kw":["prawn","malabar","kerala","fry","coastal","starter"]},
    {"en":"Chettinad Chicken Fry","bn":"চেট্টিনাড় চিকেন ফ্রাই","cat":"chicken",
     "k":214,"p":25.8,"c":4.8,"f":10.2,"fi":0.5,"ca":18,"fe":1.0,
     "kw":["chicken","chettinad","fry","south indian","spicy","starter"]},
    {"en":"Chettinad Pepper Chicken","bn":"চেট্টিনাড় পেপার চিকেন","cat":"chicken",
     "k":226,"p":24.6,"c":3.8,"f":12.0,"fi":0.6,"ca":18,"fe":1.0,
     "kw":["chicken","chettinad","pepper","dry","spicy","south indian","starter"]},
    {"en":"Chettinad Prawn Fry","bn":"চেট্টিনাড় চিংড়ি ফ্রাই","cat":"seafood",
     "k":208,"p":23.2,"c":4.8,"f":10.4,"fi":0.5,"ca":65,"fe":1.5,
     "kw":["prawn","chettinad","fry","spicy","south indian","starter"]},
    {"en":"Chettinad Fish Fry","bn":"চেট্টিনাড় ফিশ ফ্রাই","cat":"seafood",
     "k":228,"p":20.8,"c":10.5,"f":12.6,"fi":0.6,"ca":35,"fe":0.8,
     "kw":["fish","chettinad","fry","spicy","south indian","starter"]},
    {"en":"Paneer Tikka Punjabi","bn":"পাঞ্জাবি পনির টিক্কা","cat":"paneer",
     "k":265,"p":16.4,"c":8.1,"f":19.0,"fi":1.1,"ca":480,"fe":0.8,
     "kw":["paneer","punjabi","tikka","classic","tandoor","starter"]},
]

# ---------------------------------------------------------------------------
# Master list
# ---------------------------------------------------------------------------
ALL_GROUPS = [
    ("Dry Dals",         DRY_DALS),
    ("Cooked Dals",      COOKED_DALS),
    ("Dal Varieties",    DAL_VARIETIES),
    ("Chicken Dishes",   CHICKEN_DISHES),
    ("Odisha Foods",     ODISHA_FOODS),
    ("Chicken Starters", CHICKEN_STARTERS),
    ("Mutton Starters",  MUTTON_STARTERS),
    ("Seafood Starters", SEAFOOD_STARTERS),
    ("Paneer Starters",  PANEER_STARTERS),
    ("Soya Starters",    SOYA_STARTERS),
    ("Veg Starters",     VEG_STARTERS),
    ("Indo-Chinese",     INDO_CHINESE),
    ("Regional Starters",REGIONAL_STARTERS),
]

def main():
    import json, sys
    from pathlib import Path
    sys.stdout.reconfigure(encoding="utf-8")
    DATASET = Path(__file__).parent.parent / "assets" / "data" / "food_master_v8_2.json"
    data = json.loads(DATASET.read_text(encoding="utf-8"))
    before = len(data)
    print(f"Loaded {before} items")
    max_id  = max(item["id"] for item in data)
    next_id = max_id + 1
    existing = {item["en"].strip().lower() for item in data}
    added = skipped = 0
    for gname, gitems in ALL_GROUPS:
        ga = gs = 0
        for item in gitems:
            key = item["en"].strip().lower()
            if key in existing:
                gs += 1; skipped += 1
                continue
            item = dict(item)
            item["id"]  = next_id; next_id += 1
            item.setdefault("s",   "100g")
            item.setdefault("src", "local")
            data.append(item)
            existing.add(key)
            ga += 1; added += 1
        print(f"  {gname}: +{ga}, skipped {gs}")
    print(f"\nBefore:{before}  After:{len(data)}  Added:{added}  Skipped:{skipped}")
    DATASET.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Saved → {DATASET}")

if __name__ == "__main__":
    main()
