"""
add_dal_starters_v8_3.py — Add dal varieties, starters, kebabs, regional foods
"""
import json, sys
from pathlib import Path
sys.stdout.reconfigure(encoding="utf-8")

DATASET = Path(__file__).parent.parent / "assets" / "data" / "food_master_v8_2.json"

# ---------------------------------------------------------------------------
# GROUP 1: Dry dals (raw, uncooked) — per 100g
# ---------------------------------------------------------------------------
DRY_DALS = [
    {"en":"Masoor Dal (Red Lentils, Dry)","bn":"মসুর ডাল (কাঁচা)","cat":"dal",
     "k":352,"p":24.6,"c":63.4,"f":1.1,"fi":10.7,"ca":35,"fe":6.5,"mg":47,"pot":955,
     "kw":["dal","masoor","red lentil","lentil","dry","kachi","raw"]},
    {"en":"Moong Dal (Split Yellow Mung Bean, Dry)","bn":"মুগ ডাল (কাঁচা)","cat":"dal",
     "k":347,"p":24.0,"c":62.6,"f":1.2,"fi":16.3,"ca":132,"fe":6.7,"mg":189,"pot":1246,
     "kw":["dal","moong","mung","yellow","split","dry","raw"]},
    {"en":"Whole Green Moong (Dry)","bn":"গোটা মুগ (কাঁচা)","cat":"dal",
     "k":347,"p":23.9,"c":62.6,"f":1.2,"fi":16.3,"ca":132,"fe":6.7,"mg":189,"pot":1246,
     "kw":["dal","moong","mung","whole","green","dry","raw"]},
    {"en":"Chana Dal (Split Bengal Gram, Dry)","bn":"ছোলার ডাল (কাঁচা)","cat":"dal",
     "k":364,"p":20.8,"c":60.7,"f":5.6,"fi":17.4,"ca":49,"fe":4.7,"mg":166,"pot":875,
     "kw":["dal","chana","bengal gram","chickpea","split","dry","raw"]},
    {"en":"Kala Chana (Whole Black Chickpeas, Dry)","bn":"কালা চানা (কাঁচা)","cat":"dal",
     "k":364,"p":19.3,"c":60.6,"f":6.0,"fi":17.0,"ca":49,"fe":6.2,"mg":166,"pot":875,
     "kw":["dal","kala chana","black chickpea","whole","dry","raw"]},
    {"en":"Kabuli Chana (White Chickpeas, Dry)","bn":"কাবুলি চানা (কাঁচা)","cat":"dal",
     "k":364,"p":19.3,"c":60.7,"f":6.0,"fi":17.4,"ca":49,"fe":6.2,"mg":166,"pot":875,
     "kw":["dal","kabuli","chana","white chickpea","dry","raw"]},
    {"en":"Toor Dal (Arhar Dal, Split Pigeon Pea, Dry)","bn":"তুর ডাল (কাঁচা)","cat":"dal",
     "k":343,"p":22.3,"c":62.8,"f":1.7,"fi":15.0,"ca":73,"fe":5.2,"mg":183,"pot":1392,
     "kw":["dal","toor","arhar","pigeon pea","split","dry","raw"]},
    {"en":"Urad Dal (Split Black Gram, Dry)","bn":"উরদ ডাল (কাঁচা)","cat":"dal",
     "k":341,"p":25.2,"c":58.9,"f":1.6,"fi":18.3,"ca":138,"fe":7.6,"mg":267,"pot":983,
     "kw":["dal","urad","black gram","split","dry","raw"]},
    {"en":"Whole Urad (Black Gram, Dry)","bn":"গোটা উরদ (কাঁচা)","cat":"dal",
     "k":341,"p":25.2,"c":58.9,"f":1.6,"fi":18.3,"ca":138,"fe":7.6,"mg":267,"pot":983,
     "kw":["dal","urad","black gram","whole","dry","raw"]},
    {"en":"Matar Dal (Split Yellow Peas, Dry)","bn":"মটর ডাল (কাঁচা)","cat":"dal",
     "k":341,"p":24.6,"c":60.0,"f":1.2,"fi":15.0,"ca":55,"fe":4.4,"mg":115,"pot":981,
     "kw":["dal","matar","yellow peas","split","dry","raw"]},
    {"en":"Rajma (Kidney Beans, Dry)","bn":"রাজমা (কাঁচা)","cat":"dal",
     "k":333,"p":23.6,"c":60.0,"f":0.8,"fi":24.9,"ca":83,"fe":8.2,"mg":138,"pot":1359,
     "kw":["dal","rajma","kidney bean","dry","raw"]},
    {"en":"Lobia (Black-eyed Peas, Dry)","bn":"লোবিয়া (কাঁচা)","cat":"dal",
     "k":336,"p":23.5,"c":60.0,"f":1.3,"fi":10.6,"ca":77,"fe":8.3,"mg":184,"pot":1112,
     "kw":["dal","lobia","black eyed pea","cowpea","dry","raw"]},
    {"en":"Horse Gram (Kulthi Dal, Dry)","bn":"কুলথি ডাল (কাঁচা)","cat":"dal",
     "k":321,"p":22.0,"c":57.2,"f":0.5,"fi":5.3,"ca":287,"fe":6.8,"mg":311,"pot":800,
     "kw":["dal","horse gram","kulthi","dry","raw"]},
    {"en":"Soybean (Dry)","bn":"সয়াবিন (কাঁচা)","cat":"dal",
     "k":446,"p":36.5,"c":30.2,"f":19.9,"fi":9.3,"ca":277,"fe":15.7,"mg":280,"pot":1797,
     "kw":["soy","soybean","dry","raw","protein","legume"]},
]

# ---------------------------------------------------------------------------
# GROUP 2: Cooked dals — per 100g
# ---------------------------------------------------------------------------
COOKED_DALS = [
    {"en":"Masoor Dal (Cooked)","bn":"মসুর ডাল (রান্না)","cat":"dal",
     "k":116,"p":9.0,"c":20.1,"f":0.4,"fi":7.9,"ca":19,"fe":3.3,
     "kw":["dal","masoor","red lentil","cooked","boiled"]},
    {"en":"Moong Dal (Cooked)","bn":"মুগ ডাল (রান্না)","cat":"dal",
     "k":105,"p":7.0,"c":19.2,"f":0.4,"fi":7.6,"ca":27,"fe":1.4,
     "kw":["dal","moong","mung","cooked","boiled"]},
    {"en":"Whole Green Moong (Cooked)","bn":"গোটা মুগ (রান্না)","cat":"dal",
     "k":105,"p":7.0,"c":19.2,"f":0.4,"fi":7.6,"ca":27,"fe":1.4,
     "kw":["dal","moong","mung","whole","cooked","boiled"]},
    {"en":"Chana Dal (Cooked)","bn":"ছোলার ডাল (রান্না)","cat":"dal",
     "k":164,"p":8.9,"c":27.4,"f":2.6,"fi":7.8,"ca":49,"fe":2.9,
     "kw":["dal","chana","bengal gram","cooked","boiled"]},
    {"en":"Kala Chana (Cooked)","bn":"কালা চানা (রান্না)","cat":"dal",
     "k":164,"p":8.9,"c":27.4,"f":2.6,"fi":7.6,"ca":49,"fe":3.1,
     "kw":["dal","kala chana","black chickpea","cooked","boiled"]},
    {"en":"Kabuli Chana (Cooked)","bn":"কাবুলি চানা (রান্না)","cat":"dal",
     "k":164,"p":8.9,"c":27.4,"f":2.6,"fi":7.6,"ca":49,"fe":3.1,
     "kw":["dal","kabuli","chana","white chickpea","cooked","boiled"]},
    {"en":"Toor Dal (Arhar Dal, Cooked)","bn":"তুর ডাল (রান্না)","cat":"dal",
     "k":112,"p":7.2,"c":19.8,"f":0.4,"fi":6.8,"ca":36,"fe":1.6,
     "kw":["dal","toor","arhar","pigeon pea","cooked","boiled"]},
    {"en":"Urad Dal (Cooked)","bn":"উরদ ডাল (রান্না)","cat":"dal",
     "k":116,"p":8.3,"c":20.5,"f":0.6,"fi":7.5,"ca":69,"fe":3.8,
     "kw":["dal","urad","black gram","cooked","boiled"]},
    {"en":"Whole Urad (Cooked)","bn":"গোটা উরদ (রান্না)","cat":"dal",
     "k":116,"p":8.3,"c":20.5,"f":0.6,"fi":7.5,"ca":69,"fe":3.8,
     "kw":["dal","urad","black gram","whole","cooked","boiled"]},
    {"en":"Matar Dal (Cooked)","bn":"মটর ডাল (রান্না)","cat":"dal",
     "k":118,"p":8.3,"c":21.1,"f":0.4,"fi":8.3,"ca":27,"fe":2.2,
     "kw":["dal","matar","yellow pea","cooked","boiled"]},
    {"en":"Rajma (Cooked)","bn":"রাজমা (রান্না)","cat":"dal",
     "k":127,"p":8.7,"c":22.8,"f":0.5,"fi":6.4,"ca":41,"fe":4.1,
     "kw":["dal","rajma","kidney bean","cooked","boiled"]},
    {"en":"Lobia (Black-eyed Peas, Cooked)","bn":"লোবিয়া (রান্না)","cat":"dal",
     "k":116,"p":7.7,"c":20.8,"f":0.5,"fi":6.5,"ca":38,"fe":4.1,
     "kw":["dal","lobia","black eyed pea","cowpea","cooked","boiled"]},
    {"en":"Horse Gram (Kulthi Dal, Cooked)","bn":"কুলথি ডাল (রান্না)","cat":"dal",
     "k":119,"p":8.2,"c":21.0,"f":0.5,"fi":5.3,"ca":143,"fe":3.4,
     "kw":["dal","horse gram","kulthi","cooked","boiled"]},
    {"en":"Soybean (Cooked)","bn":"সয়াবিন (রান্না)","cat":"dal",
     "k":173,"p":18.2,"c":9.9,"f":9.0,"fi":6.0,"ca":138,"fe":7.8,
     "kw":["soy","soybean","cooked","boiled","protein"]},
]

# ---------------------------------------------------------------------------
# GROUP 3: Dal preparations / varieties — per 100g (estimated)
# ---------------------------------------------------------------------------
DAL_VARIETIES = [
    {"en":"Plain Masoor Dal","bn":"সাদা মসুর ডাল","cat":"dal",
     "k":116,"p":9.0,"c":20.1,"f":0.4,"fi":7.9,"ca":19,"fe":3.3,
     "kw":["dal","masoor","plain","simple","red lentil"]},
    {"en":"Plain Moong Dal","bn":"সাদা মুগ ডাল","cat":"dal",
     "k":105,"p":7.0,"c":19.2,"f":0.4,"fi":7.6,"ca":27,"fe":1.4,
     "kw":["dal","moong","plain","simple","yellow"]},
    {"en":"Bhaja Moong Dal","bn":"ভাজা মুগ ডাল","cat":"dal",
     "k":132,"p":7.2,"c":19.5,"f":2.8,"fi":6.8,"ca":25,"fe":1.4,
     "kw":["dal","moong","bhaja","roasted","bengali"]},
    {"en":"Sona Moong Dal","bn":"সোনা মুগ ডাল","cat":"dal",
     "k":108,"p":7.0,"c":19.5,"f":0.8,"fi":7.0,"ca":26,"fe":1.4,
     "kw":["dal","moong","sona","golden","bengali"]},
    {"en":"Masoor Dal Tadka","bn":"মসুর ডাল তড়কা","cat":"dal",
     "k":145,"p":8.5,"c":19.5,"f":4.0,"fi":7.0,"ca":18,"fe":3.0,
     "kw":["dal","masoor","tadka","tempered","north indian"]},
    {"en":"Dal Tadka","bn":"ডাল তড়কা","cat":"dal",
     "k":138,"p":7.0,"c":19.5,"f":3.8,"fi":6.5,"ca":35,"fe":1.8,
     "kw":["dal","tadka","toor","tempered","north indian","restaurant"]},
    {"en":"Dhaba Dal Tadka","bn":"ঢাবা ডাল তড়কা","cat":"dal",
     "k":158,"p":7.5,"c":19.0,"f":6.5,"fi":6.0,"ca":32,"fe":1.8,
     "kw":["dal","dhaba","tadka","punjabi","highway","smoky"]},
    {"en":"Dal Fry","bn":"ডাল ফ্রাই","cat":"dal",
     "k":152,"p":6.8,"c":18.5,"f":6.0,"fi":5.8,"ca":30,"fe":1.6,
     "kw":["dal","fry","toor","north indian","restaurant","popular"]},
    {"en":"Yellow Dal Fry","bn":"হলুদ ডাল ফ্রাই","cat":"dal",
     "k":142,"p":6.5,"c":19.0,"f":5.0,"fi":6.0,"ca":25,"fe":1.4,
     "kw":["dal","yellow","fry","moong","toor","north indian"]},
    {"en":"Dal Makhani","bn":"ডাল মাখনি","cat":"dal",
     "k":165,"p":8.5,"c":16.0,"f":9.0,"fi":5.0,"ca":60,"fe":3.5,
     "kw":["dal","makhani","butter","cream","urad","rajma","punjabi","rich"]},
    {"en":"Panchmel Dal","bn":"পাঁচমেল ডাল","cat":"dal",
     "k":135,"p":7.5,"c":19.5,"f":4.5,"fi":7.0,"ca":40,"fe":2.5,
     "kw":["dal","panchmel","five dal","rajasthani","mixed"]},
    {"en":"Gujarati Dal","bn":"গুজরাটি ডাল","cat":"dal",
     "k":125,"p":6.5,"c":20.5,"f":2.5,"fi":5.5,"ca":35,"fe":1.5,
     "kw":["dal","gujarati","sweet sour","toor","jaggery"]},
    {"en":"Sindhi Dal","bn":"সিন্ধি ডাল","cat":"dal",
     "k":172,"p":9.0,"c":26.0,"f":4.5,"fi":7.0,"ca":48,"fe":2.8,
     "kw":["dal","sindhi","chana","spiced"]},
    {"en":"Amti Dal","bn":"আমটি ডাল","cat":"dal",
     "k":120,"p":6.8,"c":19.5,"f":2.5,"fi":6.5,"ca":32,"fe":1.6,
     "kw":["dal","amti","maharashtrian","toor","kokum"]},
    {"en":"Varan","bn":"বরণ","cat":"dal",
     "k":112,"p":7.2,"c":19.8,"f":0.4,"fi":6.8,"ca":36,"fe":1.6,
     "kw":["dal","varan","maharashtrian","plain","toor"]},
    {"en":"Sambar","bn":"সাম্বার","cat":"dal",
     "k":74,"p":4.5,"c":11.8,"f":1.8,"fi":3.5,"ca":42,"fe":1.2,
     "kw":["dal","sambar","south indian","toor","vegetable","soup"]},
    {"en":"Rasam Dal","bn":"রসম ডাল","cat":"dal",
     "k":45,"p":2.5,"c":7.0,"f":1.0,"fi":1.5,"ca":18,"fe":0.8,
     "kw":["dal","rasam","south indian","thin","soup","tamarind","pepper"]},
    {"en":"Tomato Dal","bn":"টমেটো ডাল","cat":"dal",
     "k":115,"p":6.8,"c":19.5,"f":2.5,"fi":5.5,"ca":28,"fe":1.5,
     "kw":["dal","tomato","andhra","toor","tangy"]},
    {"en":"Palak Dal","bn":"পালক ডাল","cat":"dal",
     "k":110,"p":7.5,"c":16.5,"f":2.5,"fi":5.0,"ca":95,"fe":3.5,
     "kw":["dal","palak","spinach","toor","moong","iron","healthy"]},
    {"en":"Lauki Chana Dal","bn":"লাউ ছানা ডাল","cat":"dal",
     "k":138,"p":7.5,"c":22.0,"f":3.5,"fi":6.0,"ca":40,"fe":2.2,
     "kw":["dal","lauki","chana","bottle gourd","north indian"]},
    {"en":"Chana Dal Fry","bn":"ছানা ডাল ফ্রাই","cat":"dal",
     "k":185,"p":9.0,"c":26.0,"f":5.5,"fi":7.0,"ca":48,"fe":2.8,
     "kw":["dal","chana","fry","bengal gram","spiced"]},
    {"en":"Urad Dal Fry","bn":"উরদ ডাল ফ্রাই","cat":"dal",
     "k":145,"p":8.0,"c":20.0,"f":4.5,"fi":7.0,"ca":65,"fe":3.5,
     "kw":["dal","urad","fry","black gram","punjabi"]},
    {"en":"Whole Urad Dal","bn":"গোটা উরদ ডাল","cat":"dal",
     "k":130,"p":8.5,"c":20.5,"f":3.0,"fi":8.0,"ca":70,"fe":4.0,
     "kw":["dal","urad","whole","black gram","punjabi"]},
    {"en":"Rajma Curry","bn":"রাজমা কারি","cat":"dal",
     "k":148,"p":8.5,"c":22.5,"f":3.5,"fi":6.0,"ca":42,"fe":4.0,
     "kw":["dal","rajma","kidney bean","curry","north indian","punjabi"]},
    {"en":"Kala Chana Curry","bn":"কালা চানা কারি","cat":"dal",
     "k":182,"p":9.0,"c":26.0,"f":5.5,"fi":6.5,"ca":48,"fe":3.5,
     "kw":["dal","kala chana","black chickpea","curry","north indian"]},
    {"en":"Kabuli Chana Curry","bn":"কাবুলি চানা কারি","cat":"dal",
     "k":178,"p":8.5,"c":25.5,"f":5.0,"fi":6.5,"ca":48,"fe":3.2,
     "kw":["dal","kabuli","chana","white chickpea","curry","chole"]},
    {"en":"Lobia Curry","bn":"লোবিয়া কারি","cat":"dal",
     "k":138,"p":7.5,"c":20.5,"f":3.5,"fi":6.0,"ca":38,"fe":4.0,
     "kw":["dal","lobia","black eyed pea","cowpea","curry"]},
    {"en":"Horse Gram Dal","bn":"কুলথি ডাল","cat":"dal",
     "k":125,"p":8.0,"c":21.0,"f":2.5,"fi":5.0,"ca":143,"fe":3.4,
     "kw":["dal","horse gram","kulthi","south indian","healthy"]},
    {"en":"Mixed Dal","bn":"মিক্সড ডাল","cat":"dal",
     "k":122,"p":7.5,"c":20.0,"f":2.5,"fi":6.5,"ca":38,"fe":2.5,
     "kw":["dal","mixed","multi","combination","lentil"]},
    {"en":"Navratan Dal","bn":"নবরত্ন ডাল","cat":"dal",
     "k":132,"p":8.0,"c":20.5,"f":3.0,"fi":6.5,"ca":42,"fe":2.8,
     "kw":["dal","navratan","nine","mixed","north indian"]},
    {"en":"Panchratna Dal","bn":"পঞ্চরত্ন ডাল","cat":"dal",
     "k":128,"p":8.0,"c":20.0,"f":3.0,"fi":7.0,"ca":40,"fe":2.8,
     "kw":["dal","panchratna","five lentil","rajasthani","mixed"]},
    {"en":"Dal Palak","bn":"ডাল পালক","cat":"dal",
     "k":110,"p":7.5,"c":16.5,"f":2.5,"fi":5.0,"ca":95,"fe":3.5,
     "kw":["dal","palak","spinach","iron","healthy","north indian"]},
    {"en":"Dal Spinach Soup","bn":"ডাল পালং স্যুপ","cat":"dal",
     "k":85,"p":5.5,"c":13.0,"f":1.5,"fi":3.5,"ca":70,"fe":2.5,
     "kw":["dal","spinach","soup","healthy","fusion","light"]},
    {"en":"Bengali Tok Dal","bn":"বাংলা টক ডাল","cat":"dal",
     "k":115,"p":8.5,"c":19.5,"f":1.5,"fi":7.0,"ca":18,"fe":3.2,
     "kw":["dal","tok","sour","bengali","masoor","moong","tamarind","lemon"]},
    {"en":"Aam Dal","bn":"আম ডাল","cat":"dal",
     "k":115,"p":6.5,"c":21.0,"f":0.8,"fi":6.5,"ca":25,"fe":1.4,
     "kw":["dal","aam","mango","bengali","seasonal","summer","moong"]},
    {"en":"Tetor Dal","bn":"তেতো ডাল","cat":"dal",
     "k":108,"p":7.0,"c":19.0,"f":1.5,"fi":7.0,"ca":20,"fe":3.0,
     "kw":["dal","tetor","bitter","bengali","bitter gourd","masoor"]},
    {"en":"Motor Dal","bn":"মটর ডাল","cat":"dal",
     "k":115,"p":8.0,"c":20.5,"f":1.5,"fi":7.5,"ca":25,"fe":2.2,
     "kw":["dal","motor","matar","yellow pea","bengali"]},
    {"en":"Biulir Dal","bn":"বিউলির ডাল","cat":"dal",
     "k":120,"p":8.0,"c":20.0,"f":2.0,"fi":7.0,"ca":65,"fe":3.5,
     "kw":["dal","biuli","urad","black gram","bengali"]},
    {"en":"Cholar Dal","bn":"ছোলার ডাল","cat":"dal",
     "k":182,"p":8.5,"c":28.0,"f":5.5,"fi":6.5,"ca":50,"fe":2.8,
     "kw":["dal","cholar","chana","bengali","coconut","festive","puja"]},
]

# ---------------------------------------------------------------------------
# GROUP 4: Chicken dishes (German names → Bengali) — per 100g
# ---------------------------------------------------------------------------
CHICKEN_DISHES = [
    {"en":"Grilled Chicken Breast","bn":"গ্রিলড চিকেন ব্রেস্ট","cat":"chicken",
     "k":165,"p":31.0,"c":0.0,"f":3.6,"fi":0.0,"ca":11,"fe":0.9,
     "kw":["chicken","grilled","breast","low fat","lean","protein"]},
    {"en":"Roasted Chicken","bn":"রোস্টেড চিকেন","cat":"chicken",
     "k":215,"p":27.0,"c":0.0,"f":11.5,"fi":0.0,"ca":15,"fe":1.2,
     "kw":["chicken","roasted","whole","juicy"]},
    {"en":"Chicken Schnitzel","bn":"চিকেন শ্নিটজেল","cat":"chicken",
     "k":265,"p":23.0,"c":14.0,"f":13.0,"fi":1.0,"ca":30,"fe":1.2,
     "kw":["chicken","schnitzel","breaded","fried","european"]},
    {"en":"Chicken Cordon Bleu","bn":"চিকেন কর্ডন ব্লু","cat":"chicken",
     "k":295,"p":22.0,"c":12.0,"f":18.0,"fi":1.0,"ca":80,"fe":1.0,
     "kw":["chicken","cordon bleu","stuffed","cheese","ham","european"]},
    {"en":"Chicken Nuggets","bn":"চিকেন নাগেটস","cat":"chicken",
     "k":296,"p":15.0,"c":20.0,"f":18.0,"fi":1.2,"ca":15,"fe":1.0,
     "kw":["chicken","nuggets","fried","fast food","kids","popular"]},
    {"en":"Chicken Wings (Roasted)","bn":"চিকেন উইংস","cat":"chicken",
     "k":266,"p":23.0,"c":0.0,"f":19.0,"fi":0.0,"ca":15,"fe":1.2,
     "kw":["chicken","wings","roasted","party","spicy"]},
    {"en":"Chicken Drumsticks (Roasted)","bn":"চিকেন ড্রামস্টিক","cat":"chicken",
     "k":216,"p":27.0,"c":0.0,"f":11.0,"fi":0.0,"ca":12,"fe":1.2,
     "kw":["chicken","drumstick","leg","roasted"]},
    {"en":"Chicken Thigh (Skinless, Roasted)","bn":"চিকেন থাই","cat":"chicken",
     "k":209,"p":26.0,"c":0.0,"f":11.0,"fi":0.0,"ca":12,"fe":1.3,
     "kw":["chicken","thigh","skinless","roasted","juicy"]},
    {"en":"Chicken Breast in Cream Sauce","bn":"চিকেন ব্রেস্ট ক্রিম সস","cat":"chicken",
     "k":220,"p":24.0,"c":4.0,"f":12.0,"fi":0.3,"ca":40,"fe":0.8,
     "kw":["chicken","breast","cream sauce","rich","european"]},
    {"en":"Chicken Fricassee","bn":"চিকেন ফ্রিকাসি","cat":"chicken",
     "k":145,"p":13.0,"c":8.0,"f":7.0,"fi":1.0,"ca":35,"fe":0.9,
     "kw":["chicken","fricassee","stew","french","creamy"]},
    {"en":"Chicken Kebab","bn":"চিকেন কাবাব","cat":"chicken",
     "k":185,"p":23.0,"c":2.0,"f":9.0,"fi":0.0,"ca":15,"fe":1.0,
     "kw":["chicken","kebab","skewer","grilled","tandoori"]},
    {"en":"Chicken Döner (Meat Only)","bn":"চিকেন ডোনার","cat":"chicken",
     "k":195,"p":22.0,"c":2.0,"f":10.0,"fi":0.0,"ca":15,"fe":1.0,
     "kw":["chicken","doner","kebab","wrap","shawarma"]},
    {"en":"Chicken Sausage","bn":"চিকেন সসেজ","cat":"chicken",
     "k":220,"p":18.0,"c":2.0,"f":16.0,"fi":0.0,"ca":20,"fe":1.0,
     "kw":["chicken","sausage","processed","breakfast"]},
    {"en":"Chicken Meatballs","bn":"চিকেন মিটবল","cat":"chicken",
     "k":205,"p":20.0,"c":8.0,"f":10.0,"fi":0.8,"ca":25,"fe":1.2,
     "kw":["chicken","meatball","minced","baked","fried"]},
    {"en":"Chicken Burger Patty","bn":"চিকেন বার্গার প্যাটি","cat":"chicken",
     "k":230,"p":20.0,"c":8.0,"f":13.0,"fi":0.8,"ca":20,"fe":1.2,
     "kw":["chicken","burger","patty","fast food","fried"]},
    {"en":"Fried Chicken","bn":"ফ্রাইড চিকেন","cat":"chicken",
     "k":285,"p":23.0,"c":10.0,"f":17.0,"fi":0.8,"ca":15,"fe":1.3,
     "kw":["chicken","fried","crispy","fast food","kfc style"]},
    {"en":"Chicken Cutlet","bn":"চিকেন কাটলেট","cat":"chicken",
     "k":250,"p":22.0,"c":10.0,"f":14.0,"fi":0.8,"ca":20,"fe":1.2,
     "kw":["chicken","cutlet","breaded","bengali","fried","snack"]},
    {"en":"Chicken Stir Fry","bn":"চিকেন স্টার ফ্রাই","cat":"chicken",
     "k":145,"p":19.0,"c":5.0,"f":5.0,"fi":2.0,"ca":25,"fe":1.0,
     "kw":["chicken","stir fry","chinese","vegetables","quick","healthy"]},
    {"en":"Chicken Salad","bn":"চিকেন সালাদ","cat":"chicken",
     "k":140,"p":18.0,"c":4.0,"f":6.0,"fi":1.5,"ca":25,"fe":0.8,
     "kw":["chicken","salad","healthy","low cal","grilled","light"]},
    {"en":"Smoked Chicken","bn":"স্মোকড চিকেন","cat":"chicken",
     "k":180,"p":28.0,"c":0.0,"f":7.0,"fi":0.0,"ca":12,"fe":1.0,
     "kw":["chicken","smoked","bbq","high protein"]},
    {"en":"Chicken Liver","bn":"চিকেন লিভার","cat":"chicken",
     "k":167,"p":24.0,"c":1.0,"f":6.0,"fi":0.0,"ca":12,"fe":9.5,
     "kw":["chicken","liver","organ","iron","vitamin a","high iron"]},
    {"en":"Chicken Fricassee","bn":"চিকেন ফ্রিকাসি","cat":"chicken",
     "k":145,"p":13.0,"c":8.0,"f":7.0,"fi":1.0,"ca":35,"fe":0.9,
     "kw":["chicken","fricassee","stew","creamy"]},
]

# ---------------------------------------------------------------------------
# GROUP 5: Odisha street foods and desserts — per 100g
# ---------------------------------------------------------------------------
ODISHA_FOODS = [
    {"en":"Dahi Bara Aloo Dum","bn":"দহি বড়া আলু দম","cat":"street_food",
     "k":165,"p":5.6,"c":24.3,"f":5.4,"fi":2.8,"ca":80,"fe":1.2,
     "kw":["street food","dahi","bara","aloo dum","odia","odisha","yogurt"]},
    {"en":"Bara","bn":"বড়া","cat":"street_food",
     "k":215,"p":8.3,"c":25.8,"f":8.6,"fi":3.5,"ca":40,"fe":2.0,
     "kw":["street food","bara","odia","odisha","lentil","fried","dahi bara"]},
    {"en":"Aloo Dum","bn":"আলু দম","cat":"street_food",
     "k":118,"p":2.3,"c":18.4,"f":4.2,"fi":2.7,"ca":20,"fe":0.8,
     "kw":["street food","aloo","dum","potato","spicy","odia","odisha"]},
    {"en":"Ghuguni","bn":"ঘুঘুনি","cat":"street_food",
     "k":132,"p":6.9,"c":19.8,"f":3.1,"fi":5.8,"ca":38,"fe":3.5,
     "kw":["street food","ghuguni","peas","bengali","odia","chaat"]},
    {"en":"Gupchup (Pani Puri)","bn":"গুপচুপ","cat":"street_food",
     "k":182,"p":4.2,"c":34.5,"f":3.2,"fi":2.4,"ca":25,"fe":1.5,
     "kw":["street food","gupchup","pani puri","fuchka","odia","odisha"]},
    {"en":"Mudhi Mansa","bn":"মুড়ি মাংস","cat":"street_food",
     "k":205,"p":15.8,"c":16.3,"f":8.7,"fi":1.8,"ca":20,"fe":1.5,
     "kw":["street food","mudhi","mansa","puffed rice","mutton","odia","odisha"]},
    {"en":"Mudhi Mixture","bn":"মুড়ি মিক্সচার","cat":"street_food",
     "k":352,"p":8.5,"c":58.4,"f":10.6,"fi":5.1,"ca":30,"fe":2.0,
     "kw":["street food","mudhi","mixture","puffed rice","snack","odia"]},
    {"en":"Chhena Poda","bn":"ছেনা পোড়া","cat":"sweet",
     "k":305,"p":11.4,"c":28.5,"f":16.8,"fi":0.2,"ca":200,"fe":0.5,
     "kw":["sweet","dessert","chhena","poda","burnt cheese","odia","odisha","paneer"]},
    {"en":"Chhena Gaja","bn":"ছেনা গজা","cat":"sweet",
     "k":392,"p":8.1,"c":47.3,"f":18.5,"fi":0.3,"ca":180,"fe":0.4,
     "kw":["sweet","dessert","chhena","gaja","odia","odisha","mithai"]},
    {"en":"Rasabali","bn":"রসাবলি","cat":"sweet",
     "k":286,"p":7.2,"c":34.6,"f":12.4,"fi":0.2,"ca":200,"fe":0.4,
     "kw":["sweet","dessert","rasabali","odia","odisha","milk","syrup"]},
    {"en":"Chhena Jhili","bn":"ছেনা ঝিলি","cat":"sweet",
     "k":328,"p":8.6,"c":42.3,"f":14.3,"fi":0.2,"ca":190,"fe":0.4,
     "kw":["sweet","dessert","chhena","jhili","odia","odisha","fried","mithai"]},
    {"en":"Kakara Pitha","bn":"কাকরা পিঠা","cat":"street_food",
     "k":278,"p":5.2,"c":46.8,"f":8.3,"fi":2.1,"ca":20,"fe":1.0,
     "kw":["pitha","kakara","odia","odisha","rice","coconut","fried"]},
    {"en":"Arisa Pitha","bn":"আরিসা পিঠা","cat":"street_food",
     "k":382,"p":5.1,"c":63.2,"f":12.3,"fi":1.4,"ca":15,"fe":1.0,
     "kw":["pitha","arisa","odia","odisha","rice","jaggery","fried"]},
    {"en":"Enduri Pitha","bn":"এন্দুরি পিঠা","cat":"street_food",
     "k":218,"p":6.3,"c":39.6,"f":4.5,"fi":2.3,"ca":30,"fe":1.2,
     "kw":["pitha","enduri","odia","odisha","steamed","turmeric leaf","coconut"]},
    {"en":"Chakuli Pitha","bn":"চাকুলি পিঠা","cat":"street_food",
     "k":176,"p":5.2,"c":31.7,"f":2.6,"fi":1.8,"ca":15,"fe":0.8,
     "kw":["pitha","chakuli","odia","odisha","rice","crepe","breakfast"]},
    {"en":"Poda Pitha","bn":"পোড়া পিঠা","cat":"street_food",
     "k":265,"p":6.2,"c":47.5,"f":6.5,"fi":2.3,"ca":20,"fe":1.2,
     "kw":["pitha","poda","odia","odisha","baked","jaggery","coconut"]},
    {"en":"Manda Pitha","bn":"মান্দা পিঠা","cat":"street_food",
     "k":214,"p":4.6,"c":42.4,"f":3.2,"fi":2.0,"ca":15,"fe":0.8,
     "kw":["pitha","manda","odia","odisha","steamed","dumpling","coconut"]},
    {"en":"Chitou Pitha","bn":"চিতউ পিঠা","cat":"street_food",
     "k":170,"p":4.8,"c":32.5,"f":2.1,"fi":1.5,"ca":12,"fe":0.6,
     "kw":["pitha","chitou","odia","odisha","rice","thin","breakfast"]},
    {"en":"Suji Kakara","bn":"সুজি কাকরা","cat":"street_food",
     "k":295,"p":5.0,"c":48.5,"f":9.5,"fi":1.6,"ca":18,"fe":1.0,
     "kw":["suji","kakara","semolina","odia","odisha","fried","sweet"]},
    {"en":"Chhena Tarkari","bn":"ছেনা তরকারি","cat":"street_food",
     "k":185,"p":10.2,"c":8.8,"f":12.5,"fi":2.2,"ca":190,"fe":0.6,
     "kw":["chhena","tarkari","paneer","curry","odia","odisha"]},
    {"en":"Dalma","bn":"ডালমা","cat":"street_food",
     "k":118,"p":5.6,"c":16.2,"f":3.2,"fi":4.1,"ca":40,"fe":2.0,
     "kw":["dalma","dal","vegetable","odia","odisha","toor","healthy"]},
    {"en":"Santula","bn":"সান্তুলা","cat":"street_food",
     "k":82,"p":2.6,"c":10.5,"f":3.3,"fi":3.6,"ca":30,"fe":1.0,
     "kw":["santula","vegetable","odia","odisha","mixed veg","healthy"]},
    {"en":"Chaat with Ghuguni","bn":"চাট ঘুঘুনি","cat":"street_food",
     "k":158,"p":6.4,"c":24.2,"f":4.1,"fi":4.5,"ca":35,"fe":2.5,
     "kw":["chaat","ghuguni","street food","odia","bengali","tangy"]},
    {"en":"Egg Chop","bn":"ডিমের চপ","cat":"street_food",
     "k":248,"p":10.8,"c":20.2,"f":13.4,"fi":2.0,"ca":40,"fe":1.5,
     "kw":["egg","chop","fried","street food","bengali","odia","snack"]},
    {"en":"Vegetable Chop","bn":"সবজির চপ","cat":"street_food",
     "k":214,"p":5.3,"c":27.6,"f":9.4,"fi":3.6,"ca":30,"fe":1.2,
     "kw":["vegetable","chop","fried","street food","bengali","snack"]},
    {"en":"Singada (Samosa)","bn":"সিঙ্গাড়া","cat":"street_food",
     "k":262,"p":5.3,"c":30.8,"f":13.6,"fi":2.7,"ca":20,"fe":1.2,
     "kw":["singada","samosa","fried","odia","bengali","street food","potato"]},
    {"en":"Pakoda","bn":"পাকোড়া","cat":"street_food",
     "k":285,"p":7.1,"c":24.4,"f":17.6,"fi":3.4,"ca":50,"fe":1.5,
     "kw":["pakoda","fritter","fried","snack","street food","besan"]},
    {"en":"Bread Pakoda","bn":"ব্রেড পাকোড়া","cat":"street_food",
     "k":295,"p":7.8,"c":31.5,"f":15.2,"fi":2.6,"ca":40,"fe":1.2,
     "kw":["bread","pakoda","fried","snack","street food","besan"]},
    {"en":"Aloo Chop","bn":"আলুর চপ","cat":"street_food",
     "k":232,"p":4.8,"c":28.4,"f":11.2,"fi":3.1,"ca":20,"fe":1.0,
     "kw":["aloo","chop","potato","fried","street food","bengali","odia"]},
    {"en":"Chhena Bara","bn":"ছেনা বড়া","cat":"street_food",
     "k":254,"p":10.5,"c":18.6,"f":15.4,"fi":0.8,"ca":185,"fe":0.5,
     "kw":["chhena","bara","paneer","fried","odia","odisha","street food"]},
]
