import json, sys
sys.stdout.reconfigure(encoding='utf-8')

with open('assets/data/food_master_v7_0.json', encoding='utf-8') as f:
    data = json.load(f)

recategorize = {
    # SOUP
    'al yakhani': 'soup',
    'almond soup': 'soup',
    'brown stock': 'soup',
    'consomme au julienne': 'soup',
    'meat consomme': 'soup',
    'meat stock': 'soup',
    'mixed stock': 'soup',
    'vegetable stock': 'soup',
    'vegetable yakhni': 'soup',
    'weight loss soup': 'soup',
    'white stock': 'soup',

    # VEGETABLE
    'avial': 'vegetable',
    'baked vegetables': 'vegetable',
    'bathua bhujia': 'vegetable',
    'beans foogath': 'vegetable',
    'beans with coconut': 'vegetable',
    'besan bathua chilla/cheela': 'vegetable',
    'besan gatte curry': 'vegetable',
    'besan kadhi with pakodies': 'vegetable',
    'broccoli delight': 'vegetable',
    'carrot and fenugreek leaves': 'vegetable',
    'dry arbi': 'vegetable',
    'fricassee of mushroom': 'vegetable',
    'lotus stem curry': 'vegetable',
    'masala arbi': 'vegetable',
    'methi chaman': 'vegetable',
    'mooli bhujia': 'vegetable',
    'mushroom matar': 'vegetable',
    'pea curry': 'vegetable',
    'pea kofta curry': 'vegetable',
    'pea mushroom curry': 'vegetable',
    'pea vadi curry': 'vegetable',
    'sarson ka saag': 'vegetable',
    'sauteed radishes with green beans': 'vegetable',
    'stuffed baked potatoes': 'vegetable',
    'stuffed bittergourd': 'vegetable',
    'stuffed capsicum': 'vegetable',
    'stuffed round gourd': 'vegetable',
    'stuffed tomatoes': 'vegetable',
    'vegetable jalfrezi': 'vegetable',
    'vegetable mix': 'vegetable',
    'vegetables stir fry': 'vegetable',
    'yam fried': 'vegetable',
    'yam kofta curry': 'vegetable',
    'sajina': 'vegetable',
    'vegetarian nargisi kofta curry': 'vegetable',
    'simple veg meal': 'vegetable',
    'healthy curry bowl': 'vegetable',
    'pickled mustard greens': 'vegetable',
    'aloo bhaja': 'vegetable',
    'beguni': 'vegetable',

    # LEGUME
    'black channa curry/bengal gram curry': 'legume',
    'chickpeas curry': 'legume',
    'classic seasoned black beans': 'legume',
    'fermented bengal gram vada': 'legume',
    'ghugni': 'legume',
    'green gram whole with baghar': 'legume',
    'kabuli channa curry': 'legume',
    'khatta channa': 'legume',
    'kidney bean curry': 'legume',
    'lobia curry': 'legume',
    'soyabean curry': 'legume',
    'soyabean muthias': 'legume',
    'soyabean tikki': 'legume',
    'whole moth': 'legume',
    'dhansak': 'legume',
    'roasted chana': 'legume',
    'pulse mix': 'legume',

    # NOODLE
    'beans and macaroni': 'noodle',
    'chicken chowmein': 'noodle',
    'classic italian pasta': 'noodle',
    'egg chowmein': 'noodle',
    'lasagne with meat sauce': 'noodle',
    'meat and macaroni casserole': 'noodle',
    'pasta hot pot': 'noodle',
    'penne platter': 'noodle',
    'spaghetti bolognese': 'noodle',
    'spaghetti with meat balls and tomato sauce': 'noodle',
    'vegetable chowmein': 'noodle',

    # BREAD / SANDWICH / ROLL
    'carrot apple sandwich': 'bread',
    'checker board sandwich': 'bread',
    'chicken roll': 'bread',
    'chicken sandwich': 'bread',
    'classic club sandwich': 'bread',
    'club sandwich': 'bread',
    'cucumber sandwich': 'bread',
    'danish luncheon sandwich': 'bread',
    'egg sandwich': 'bread',
    'egg roll kolkata style': 'bread',
    'french sandwich': 'bread',
    'kathi roll chicken': 'bread',
    'pin wheel sandwich': 'bread',
    'rainbow sandwich': 'bread',
    'ribbon sandwich': 'bread',
    'rolled sandwich': 'bread',
    'salami sandwich': 'bread',
    'spicy chutney sandwich': 'bread',
    'submarine sandwich': 'bread',
    'sunset and sunrise open sandwich': 'bread',
    'tomato and cucumber sandwich': 'bread',
    'tomato sandwich': 'bread',
    'veg roll': 'bread',
    'veg sandwich': 'bread',
    'vegetable and mayonnaise sandwich': 'bread',
    'vegetable burger': 'bread',
    'vegetarian club sandwich': 'bread',
    'watercress sandwich': 'bread',
    'peanut and tomato sandwich': 'bread',
    'pizza': 'bread',
    'fruit loaf': 'bread',

    # EGG
    'baked eggs in tomato sauce': 'egg',
    'corn omelette/omlet': 'egg',
    'egg devil': 'egg',
    'egg devil (dimer devil)': 'egg',
    'french omelette/omlet': 'egg',
    'plain omelette/omlet': 'egg',
    'puffy omelette/omlet': 'egg',
    'spanish omelette/omlet': 'egg',

    # MEAT
    'boti kebab': 'meat',
    'dry masala chops': 'meat',
    'roghan josh': 'meat',
    'shammi kebab': 'meat',
    "shepherd's pie": 'meat',
    'simple chicken meal': 'meat',

    # FISH
    'chingri cutlet': 'fish',

    # DESSERT
    'american frosting': 'dessert',
    'apricot fool': 'dessert',
    'assorted pastry': 'dessert',
    'black forest pastry': 'dessert',
    'charlotte rousse': 'dessert',
    'chocolate eclairs': 'dessert',
    'chocolate glace icing': 'dessert',
    'chocolate meringue pie': 'dessert',
    'chocolate pastry': 'dessert',
    'chocolate souffle': 'dessert',
    'chocolate swiss roll': 'dessert',
    'choux pastry': 'dessert',
    'choux swans': 'dessert',
    'cold chocolate souffle': 'dessert',
    'cold lemon souffle': 'dessert',
    'cold vanilla souffle': 'dessert',
    'date and nut pie': 'dessert',
    'flaky pastry': 'dessert',
    'flan pastry': 'dessert',
    'fruit flan': 'dessert',
    'glace icing': 'dessert',
    'gum icing': 'dessert',
    'hot chocolate souffle': 'dessert',
    'hot lemon souffle': 'dessert',
    'hot vanilla souffle': 'dessert',
    'kulfi': 'dessert',
    'lemon chiffon pie': 'dessert',
    'lemon meringue pie': 'dessert',
    'lemon souffle': 'dessert',
    'masala souffle': 'dessert',
    'pavlova': 'dessert',
    'phirni': 'dessert',
    'royal icing': 'dessert',
    'shahi tukre': 'dessert',
    'short crust pastry': 'dessert',
    'swiss roll': 'dessert',
    'vanilla souffle': 'dessert',
    'jam filling': 'dessert',

    # SWEET
    'almond biscuit': 'sweet',
    'arisa pitha': 'sweet',
    'butterfly biscuit': 'sweet',
    'buttermilk biscuit': 'sweet',
    'cardamom cookies': 'sweet',
    'cashewnut burfi': 'sweet',
    'chenna murki': 'sweet',
    'chum chum': 'sweet',
    'chocolate burfi': 'sweet',
    'chocolate chip cookies': 'sweet',
    'chocolate walnut cookies': 'sweet',
    'christmas bell biscuit': 'sweet',
    'christmas biscuit': 'sweet',
    'christmas star biscuit': 'sweet',
    'christmas tree biscuit': 'sweet',
    'christmas wreath biscuit': 'sweet',
    'coconut biscuit': 'sweet',
    'coffee biscuit': 'sweet',
    'cranberry cookies': 'sweet',
    'crunchy butterscotch': 'sweet',
    'danedar burfi': 'sweet',
    'danish cookies': 'sweet',
    'finger millet biscuit': 'sweet',
    'ginger biscuit': 'sweet',
    'ginger candy': 'sweet',
    'gingerman biscuit': 'sweet',
    'gram flour burfi': 'sweet',
    'greenpea cookies': 'sweet',
    'hazelnut cookies': 'sweet',
    'ice box cookies': 'sweet',
    'jelly biscuit': 'sweet',
    'kesari bath': 'sweet',
    'lemon cookies': 'sweet',
    'mal pua': 'sweet',
    'manda pitha': 'sweet',
    'masala biscuit': 'sweet',
    'melting moments': 'sweet',
    'murir moa': 'sweet',
    'murmura chikki': 'sweet',
    'odia gaja': 'sweet',
    'odia khaja': 'sweet',
    'olive biscuit': 'sweet',
    'orange biscuit': 'sweet',
    'peanut brittle': 'sweet',
    'peanut burfi': 'sweet',
    'peanut chikki': 'sweet',
    'plain burfi': 'sweet',
    'putharekulu': 'sweet',
    'rajbogh': 'sweet',
    'rasbhari': 'sweet',
    'raspberry shortbread cookies': 'sweet',
    'saffron biscuit': 'sweet',
    'semolina burfi': 'sweet',
    'sesame biscuit': 'sweet',
    'sesame chickpeas brittle': 'sweet',
    'soya chikki': 'sweet',
    'sunflower cookies': 'sweet',
    'tutti fruitti biscuit': 'sweet',
    'ghujia/lavang latika': 'sweet',
    'dil bahar': 'sweet',
    'carrot murabba': 'sweet',
    'gooseberry marmalade': 'sweet',
    'plum jam': 'sweet',
    'marmalade': 'sweet',
    'pear chocholate sunday': 'sweet',
    'fruit delight': 'sweet',
    'peach blueberry preserves': 'sweet',
    'pear preserves': 'sweet',
    'starfruit preserves': 'sweet',

    # SALAD / BOWLS
    'balanced diet bowl': 'salad',
    'coleslaw': 'salad',
    'detox bowl': 'salad',
    'fitness bowl': 'salad',
    'high protein bowl': 'salad',
    'infinity wellness bowl': 'salad',
    'light dinner bowl': 'salad',
    'light lunch bowl': 'salad',
    'low carb bowl': 'salad',
    'macaroni salad': 'salad',
    'pasta salad': 'salad',
    'tomato aspic': 'salad',
    'veg protein bowl': 'salad',
    'wellness bowl': 'salad',

    # GRAIN / PORRIDGE / KHICHDI
    'canjee': 'grain',
    'maize porridge': 'grain',
    'namkeen daliya': 'grain',
    'oatmeal porridge': 'grain',
    'plain khitchdi': 'grain',
    'sago khitchdi/khichri': 'grain',
    'semolina porridge': 'grain',
    'vermicelli porridge': 'grain',
    'shishu ahar': 'grain',

    # BREAKFAST
    'vermicelli upma': 'breakfast',

    # BEVERAGE
    'coconut milk': 'beverage',
    'flavoured milkshake': 'beverage',
    'fruit punch': 'beverage',
    'hot cocoa': 'beverage',
    'jal jeera': 'beverage',
    'lemon and ginger squash': 'beverage',
    'lem-o-gin': 'beverage',
    'lemon squash': 'beverage',
    'lemonade': 'beverage',
    'lichi squash': 'beverage',
    'mintade': 'beverage',
    'plum squash': 'beverage',
    'sattu drink': 'beverage',
    'thandai': 'beverage',

    # FRUIT
    'stewed fruit': 'fruit',
}

changed = 0
for food in data:
    en_lower = food.get('en', '').lower().strip()
    if food.get('cat') == 'snack' and en_lower in recategorize:
        food['cat'] = recategorize[en_lower]
        changed += 1

print(f'Changed: {changed} items')

from collections import Counter
cats = Counter(f.get('cat', '') for f in data)
print('\nNew category distribution:')
for cat, count in sorted(cats.items(), key=lambda x: -x[1]):
    print(f'  {cat:<20} {count}')

with open('assets/data/food_master_v7_0.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, separators=(',', ':'))
print('\nSaved successfully.')
